<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class accesosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('accesos')->truncate();

        DB::table('accesos')->insert([
            // accesos para el usuario con id_persona = 1 (id_usuario = 76 en el SQL original)
            ['id_persona' => 1, 'id_modulo' => 3, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 11, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 12, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 27, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 28, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 4, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 13, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 14, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 15, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 16, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 17, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 5, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 18, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 19, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 20, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 21, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 23, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 6, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 26, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 32, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 33, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 34, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 35, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 10, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 36, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 37, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 32, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 33, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 34, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 35, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 10, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 36, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 1, 'id_modulo' => 37, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // accesos para el usuario con id_persona = 2 (id_usuario = 83 en el SQL original)
            ['id_persona' => 2, 'id_modulo' => 11, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 32, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 12, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 27, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 28, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 13, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 14, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 15, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 16, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 17, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 23, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 20, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 18, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 19, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 26, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 33, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 34, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 35, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 30, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 31, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 10, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 36, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 2, 'id_modulo' => 37, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // accesos para el usuario con id_persona = 3 (id_usuario = 99 en el SQL original)
            ['id_persona' => 3, 'id_modulo' => 14, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 15, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 13, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 28, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 27, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 12, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 11, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 32, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 16, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 17, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 23, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 20, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 18, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 19, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 26, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 33, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 34, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 35, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 30, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 3, 'id_modulo' => 31, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // accesos para el usuario con id_persona = 4 (id_usuario = 87 en el SQL original)
            ['id_persona' => 4, 'id_modulo' => 32, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 11, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 12, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 27, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 28, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 13, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 14, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 15, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 16, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 17, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 23, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 20, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 18, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 19, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 26, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 33, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 34, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 35, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 30, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 4, 'id_modulo' => 31, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // accesos para el usuario con id_persona = 5 (id_usuario = 1 en el SQL original)
            ['id_persona' => 5, 'id_modulo' => 32, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 11, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 12, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 27, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 28, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 13, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 14, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 15, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 16, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 17, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 23, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 20, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 18, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 19, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 26, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 33, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 34, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 35, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 30, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 31, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 36, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 37, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 5, 'id_modulo' => 10, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // accesos para el usuario con id_persona = 6 (id_usuario = 101 en el SQL original)
            ['id_persona' => 6, 'id_modulo' => 3, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 11, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 12, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 27, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 28, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 4, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 13, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 14, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 15, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 16, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 17, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 5, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 18, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 19, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 20, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 21, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 23, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 6, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 26, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 32, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 33, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 34, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 35, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 10, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 6, 'id_modulo' => 36, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // accesos para el usuario con id_persona = 7 (id_usuario = 3 en el SQL original)
            ['id_persona' => 7, 'id_modulo' => 3, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 11, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 12, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 27, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 28, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 4, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 13, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 14, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 15, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 16, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 17, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 5, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 18, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 19, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 20, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 21, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 23, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 6, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 26, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 32, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 33, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 34, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 35, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 10, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 7, 'id_modulo' => 36, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // accesos para el usuario con id_persona = 8 (id_usuario = 86 en el SQL original)
            ['id_persona' => 8, 'id_modulo' => 32, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 11, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 27, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 28, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 12, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 10, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 13, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 14, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 15, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 16, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 17, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 23, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 20, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 36, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 37, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 18, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 19, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 26, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 33, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 34, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 35, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 30, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 8, 'id_modulo' => 31, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // accesos para el usuario con id_persona = 9 (id_usuario = 104 en el SQL original)
            ['id_persona' => 9, 'id_modulo' => 32, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 11, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 12, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 27, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 28, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 13, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 14, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 15, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 16, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 17, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 23, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 20, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 18, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 19, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 26, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 33, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 34, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 35, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 30, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 31, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 36, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 37, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 9, 'id_modulo' => 10, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // accesos para el usuario con id_persona = 10 (id_usuario = 120 en el SQL original)
            ['id_persona' => 10, 'id_modulo' => 32, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 11, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 27, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 28, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 12, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 10, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 13, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 14, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 15, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 16, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 17, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 23, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 20, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 36, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 37, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 18, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 19, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 26, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 33, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 34, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 35, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 30, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 10, 'id_modulo' => 31, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // accesos para el usuario con id_persona = 11 (id_usuario = 85 en el SQL original)
            ['id_persona' => 11, 'id_modulo' => 32, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 11, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 27, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 28, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 12, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 10, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 13, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 14, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 15, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 16, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 17, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 23, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 20, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 36, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 37, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 18, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 19, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 26, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 33, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 34, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 35, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 30, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 11, 'id_modulo' => 31, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // accesos para el usuario con id_persona = 12 (id_usuario = 109 en el SQL original)
            ['id_persona' => 12, 'id_modulo' => 32, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 11, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 27, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 28, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 12, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 10, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 13, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 14, 'read' => 2, 'create' => 1, 'update' => 1, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 15, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 16, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 17, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 23, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 20, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 36, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 37, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 18, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 19, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 26, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 33, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 34, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 35, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 30, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 12, 'id_modulo' => 31, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // accesos para el usuario con id_persona = 13 (id_usuario = 121 en el SQL original)
            ['id_persona' => 13, 'id_modulo' => 32, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 13, 'id_modulo' => 11, 'read' => 1, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 13, 'id_modulo' => 27, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 13, 'id_modulo' => 28, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 13, 'id_modulo' => 12, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 13, 'id_modulo' => 10, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 13, 'id_modulo' => 13, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 13, 'id_modulo' => 14, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 13, 'id_modulo' => 15, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 13, 'id_modulo' => 16, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 13, 'id_modulo' => 17, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 13, 'id_modulo' => 23, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 13, 'id_modulo' => 20, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // accesos para el usuario con id_persona = 14 (id_usuario = 141 en el SQL original)
            ['id_persona' => 14, 'id_modulo' => 47, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 14, 'id_modulo' => 35, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 14, 'id_modulo' => 34, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 14, 'id_modulo' => 33, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],

            // accesos para el usuario con id_persona = 15 (id_usuario = 142 en el SQL original)
            ['id_persona' => 15, 'id_modulo' => 57, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 15, 'id_modulo' => 56, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 15, 'id_modulo' => 55, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 15, 'id_modulo' => 21, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 15, 'id_modulo' => 18, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 15, 'id_modulo' => 37, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 15, 'id_modulo' => 36, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 15, 'id_modulo' => 20, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 15, 'id_modulo' => 23, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 15, 'id_modulo' => 17, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 15, 'id_modulo' => 16, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 15, 'id_modulo' => 15, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 15, 'id_modulo' => 14, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 15, 'id_modulo' => 13, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 15, 'id_modulo' => 10, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 15, 'id_modulo' => 12, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 15, 'id_modulo' => 11, 'read' => 2, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
            ['id_persona' => 15, 'id_modulo' => 32, 'read' => 0, 'create' => 0, 'update' => 0, 'delete' =>0, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now()],
        ]);
    }
}