<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ChoferesTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('choferes')->delete();
        
        \DB::table('choferes')->insert(array (
            0 => 
            array (
                'cargo' => 'CHOFER',
                'certificado_medico' => '5',
                'certificado_medico_vencimiento' => '2029-09-18',
                'created_at' => NULL,
                'documento_vialidad_numero' => NULL,
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'montilla.jpg',
                'id' => 1,
                'licencia_numero' => NULL,
                'licencia_vencimiento' => '2035-10-03',
                'persona_id' => 242,
                'soporte_certificado' => NULL,
                'soporte_documento' => NULL,
                'soporte_licencia' => NULL,
                'tipo_licencia' => '5',
                'updated_at' => NULL,
                'vehiculo_id' => NULL,
            ),
            1 => 
            array (
                'cargo' => 'OPERADOR DE PATIO',
                'certificado_medico' => NULL,
                'certificado_medico_vencimiento' => NULL,
                'created_at' => NULL,
                'documento_vialidad_numero' => NULL,
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'pedro.jpg',
                'id' => 2,
                'licencia_numero' => NULL,
                'licencia_vencimiento' => NULL,
                'persona_id' => 243,
                'soporte_certificado' => NULL,
                'soporte_documento' => NULL,
                'soporte_licencia' => NULL,
                'tipo_licencia' => NULL,
                'updated_at' => NULL,
                'vehiculo_id' => NULL,
            ),
            2 => 
            array (
                'cargo' => 'CHOFER',
                'certificado_medico' => '5',
                'certificado_medico_vencimiento' => '2027-04-09',
                'created_at' => NULL,
                'documento_vialidad_numero' => NULL,
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'rodolfo.jpg',
                'id' => 3,
                'licencia_numero' => NULL,
                'licencia_vencimiento' => '2027-04-07',
                'persona_id' => 244,
                'soporte_certificado' => NULL,
                'soporte_documento' => 'DOC RODOLFO.pdf',
                'soporte_licencia' => NULL,
                'tipo_licencia' => '5',
                'updated_at' => NULL,
                'vehiculo_id' => NULL,
            ),
            3 => 
            array (
                'cargo' => 'AYUDANTE',
                'certificado_medico' => NULL,
                'certificado_medico_vencimiento' => NULL,
                'created_at' => NULL,
                'documento_vialidad_numero' => NULL,
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'fredis.jpg',
                'id' => 4,
                'licencia_numero' => NULL,
                'licencia_vencimiento' => NULL,
                'persona_id' => 245,
                'soporte_certificado' => NULL,
                'soporte_documento' => 'DOC FREDIS.pdf',
                'soporte_licencia' => NULL,
                'tipo_licencia' => NULL,
                'updated_at' => NULL,
                'vehiculo_id' => NULL,
            ),
            4 => 
            array (
                'cargo' => 'CHOFER',
                'certificado_medico' => '5',
                'certificado_medico_vencimiento' => '2029-09-10',
                'created_at' => NULL,
                'documento_vialidad_numero' => '2023-05-08',
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'brenitte.jpg',
                'id' => 6,
                'licencia_numero' => '0',
                'licencia_vencimiento' => '2029-11-28',
                'persona_id' => 247,
                'soporte_certificado' => NULL,
                'soporte_documento' => 'DOC_BRENITTE[1].pdf',
                'soporte_licencia' => '0',
                'tipo_licencia' => 'TSP',
                'updated_at' => '2025-10-29 16:33:03',
                'vehiculo_id' => NULL,
            ),
            5 => 
            array (
                'cargo' => 'AYUDANTE DE CHOFER',
                'certificado_medico' => NULL,
                'certificado_medico_vencimiento' => NULL,
                'created_at' => NULL,
                'documento_vialidad_numero' => NULL,
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'rafael.jpg',
                'id' => 7,
                'licencia_numero' => NULL,
                'licencia_vencimiento' => NULL,
                'persona_id' => 248,
                'soporte_certificado' => NULL,
                'soporte_documento' => NULL,
                'soporte_licencia' => NULL,
                'tipo_licencia' => NULL,
                'updated_at' => NULL,
                'vehiculo_id' => NULL,
            ),
            6 => 
            array (
                'cargo' => 'CHOFER',
                'certificado_medico' => '5',
                'certificado_medico_vencimiento' => '2028-12-04',
                'created_at' => NULL,
                'documento_vialidad_numero' => '2023-05-08',
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'javier.jpg',
                'id' => 8,
                'licencia_numero' => NULL,
                'licencia_vencimiento' => '2033-03-19',
                'persona_id' => 249,
                'soporte_certificado' => NULL,
                'soporte_documento' => 'Certificado TORRES M. JAVIER J.pdf;Javier Certificado de Circulacion Vehiculo Pesado.pdf;licencia javier.pdf;certificadomedicojavier.pdf',
                'soporte_licencia' => NULL,
                'tipo_licencia' => 'TSP',
                'updated_at' => NULL,
                'vehiculo_id' => NULL,
            ),
            7 => 
            array (
                'cargo' => 'AYUDANTE',
                'certificado_medico' => NULL,
                'certificado_medico_vencimiento' => NULL,
                'created_at' => NULL,
                'documento_vialidad_numero' => NULL,
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'luisrocha.jpg',
                'id' => 9,
                'licencia_numero' => NULL,
                'licencia_vencimiento' => NULL,
                'persona_id' => 250,
                'soporte_certificado' => NULL,
                'soporte_documento' => NULL,
                'soporte_licencia' => NULL,
                'tipo_licencia' => NULL,
                'updated_at' => NULL,
                'vehiculo_id' => NULL,
            ),
            8 => 
            array (
                'cargo' => 'CHOFER',
                'certificado_medico' => NULL,
                'certificado_medico_vencimiento' => NULL,
                'created_at' => NULL,
                'documento_vialidad_numero' => NULL,
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'yhender.jpg',
                'id' => 10,
                'licencia_numero' => NULL,
                'licencia_vencimiento' => NULL,
                'persona_id' => 251,
                'soporte_certificado' => NULL,
                'soporte_documento' => 'DOC YHENDER.pdf',
                'soporte_licencia' => NULL,
                'tipo_licencia' => NULL,
                'updated_at' => NULL,
                'vehiculo_id' => NULL,
            ),
            9 => 
            array (
                'cargo' => 'CHOFER',
                'certificado_medico' => '5',
                'certificado_medico_vencimiento' => '2025-08-27',
                'created_at' => NULL,
                'documento_vialidad_numero' => NULL,
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'mariano.jpg',
                'id' => 11,
                'licencia_numero' => NULL,
                'licencia_vencimiento' => '2031-09-13',
                'persona_id' => 252,
                'soporte_certificado' => NULL,
                'soporte_documento' => 'DOC LUIS MARIANO.pdf',
                'soporte_licencia' => NULL,
                'tipo_licencia' => 'TSP',
                'updated_at' => NULL,
                'vehiculo_id' => NULL,
            ),
            10 => 
            array (
                'cargo' => 'AYUDANTE DE CHOFER',
                'certificado_medico' => NULL,
                'certificado_medico_vencimiento' => NULL,
                'created_at' => NULL,
                'documento_vialidad_numero' => NULL,
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'Lemir.jpg',
                'id' => 12,
                'licencia_numero' => NULL,
                'licencia_vencimiento' => NULL,
                'persona_id' => 2,
                'soporte_certificado' => NULL,
                'soporte_documento' => NULL,
                'soporte_licencia' => NULL,
                'tipo_licencia' => NULL,
                'updated_at' => NULL,
                'vehiculo_id' => NULL,
            ),
            11 => 
            array (
                'cargo' => 'CHOFER',
                'certificado_medico' => NULL,
                'certificado_medico_vencimiento' => NULL,
                'created_at' => NULL,
                'documento_vialidad_numero' => NULL,
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'ricargo.png',
                'id' => 13,
                'licencia_numero' => NULL,
                'licencia_vencimiento' => NULL,
                'persona_id' => 261,
                'soporte_certificado' => NULL,
                'soporte_documento' => 'DOCRICARDOC.pdf',
                'soporte_licencia' => NULL,
                'tipo_licencia' => NULL,
                'updated_at' => NULL,
                'vehiculo_id' => NULL,
            ),
            12 => 
            array (
                'cargo' => 'AYUDANTE DE CHOFER',
                'certificado_medico' => NULL,
                'certificado_medico_vencimiento' => NULL,
                'created_at' => NULL,
                'documento_vialidad_numero' => NULL,
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'yhender.jpg',
                'id' => 14,
                'licencia_numero' => NULL,
                'licencia_vencimiento' => NULL,
                'persona_id' => 251,
                'soporte_certificado' => NULL,
                'soporte_documento' => 'DOC YHENDER.pdf',
                'soporte_licencia' => NULL,
                'tipo_licencia' => NULL,
                'updated_at' => NULL,
                'vehiculo_id' => NULL,
            ),
            13 => 
            array (
                'cargo' => 'AYUDANTE',
                'certificado_medico' => NULL,
                'certificado_medico_vencimiento' => NULL,
                'created_at' => '2025-12-08 11:21:48',
                'documento_vialidad_numero' => NULL,
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'jose_hernandez.png',
                'id' => 16,
                'licencia_numero' => NULL,
                'licencia_vencimiento' => '2026-06-20',
                'persona_id' => 267,
                'soporte_certificado' => NULL,
                'soporte_documento' => NULL,
                'soporte_licencia' => NULL,
                'tipo_licencia' => NULL,
                'updated_at' => '2025-12-08 11:21:48',
                'vehiculo_id' => NULL,
            ),
            14 => 
            array (
                'cargo' => 'CHOFER',
                'certificado_medico' => NULL,
                'certificado_medico_vencimiento' => '2029-06-26',
                'created_at' => '2026-01-06 14:33:33',
                'documento_vialidad_numero' => NULL,
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'carranza.png',
                'id' => 17,
                'licencia_numero' => NULL,
                'licencia_vencimiento' => '2032-11-07',
                'persona_id' => 268,
                'soporte_certificado' => NULL,
                'soporte_documento' => 'DENNYS CARRANZA 2 LIC.pdf;DENNYS CARRANZA CI LIC.pdf',
                'soporte_licencia' => NULL,
                'tipo_licencia' => '5',
                'updated_at' => NULL,
                'vehiculo_id' => NULL,
            ),
            15 => 
            array (
                'cargo' => 'AYUDANTE DE CHOFER',
                'certificado_medico' => NULL,
                'certificado_medico_vencimiento' => NULL,
                'created_at' => '2026-01-06 14:33:33',
                'documento_vialidad_numero' => NULL,
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'madinson.png',
                'id' => 18,
                'licencia_numero' => NULL,
                'licencia_vencimiento' => '2035-08-26',
                'persona_id' => 272,
                'soporte_certificado' => NULL,
                'soporte_documento' => 'MADINSON CEDULA.pdf;MADINSON LICENCIA.pdf',
                'soporte_licencia' => NULL,
                'tipo_licencia' => '5',
                'updated_at' => NULL,
                'vehiculo_id' => NULL,
            ),
            16 => 
            array (
                'cargo' => 'CHOFER',
                'certificado_medico' => NULL,
                'certificado_medico_vencimiento' => '2030-07-19',
                'created_at' => '2026-01-06 14:33:33',
                'documento_vialidad_numero' => NULL,
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'hugo_medina.png',
                'id' => 20,
                'licencia_numero' => NULL,
                'licencia_vencimiento' => '2026-05-11',
                'persona_id' => 274,
                'soporte_certificado' => NULL,
                'soporte_documento' => 'HUGO HERNANDEZ CI LIC.pdf',
                'soporte_licencia' => NULL,
                'tipo_licencia' => '5',
                'updated_at' => NULL,
                'vehiculo_id' => NULL,
            ),
            17 => 
            array (
                'cargo' => 'AYUDANTE DE CHOFER',
                'certificado_medico' => NULL,
                'certificado_medico_vencimiento' => NULL,
                'created_at' => '2026-01-06 14:33:33',
                'documento_vialidad_numero' => NULL,
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'correia.png',
                'id' => 21,
                'licencia_numero' => NULL,
                'licencia_vencimiento' => NULL,
                'persona_id' => 275,
                'soporte_certificado' => NULL,
                'soporte_documento' => 'JEAN CARLOS CORREIA ci.pdf',
                'soporte_licencia' => NULL,
                'tipo_licencia' => NULL,
                'updated_at' => NULL,
                'vehiculo_id' => NULL,
            ),
            18 => 
            array (
                'cargo' => 'CHOFER',
                'certificado_medico' => '5',
                'certificado_medico_vencimiento' => '2029-09-18',
                'created_at' => NULL,
                'documento_vialidad_numero' => NULL,
                'documento_vialidad_vencimiento' => NULL,
                'foto' => 'daniel_infante.png',
                'id' => 22,
                'licencia_numero' => NULL,
                'licencia_vencimiento' => '2035-10-03',
                'persona_id' => 276,
                'soporte_certificado' => NULL,
                'soporte_documento' => 'infantecedula.jpeg;infantelicencia.jpeg',
                'soporte_licencia' => NULL,
                'tipo_licencia' => '5',
                'updated_at' => NULL,
                'vehiculo_id' => NULL,
            ),
        ));
        
        
    }
}