<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ComprasCombustibleTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        DB::table('compras_combustible')->delete();
        
        DB::table('compras_combustible')->insert(array (
            0 => 
            array (
                'cantidad_litros' => 38000,
                'cantidad_recibida' => NULL,
                'cisterna' => NULL,
                'created_at' => '2025-11-12 17:27:31',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2025-11-13',
                'flete' => 1,
                'id' => 20,
                'observaciones' => 'flete suministros garcia',
                'otro_ayudante' => 'N/A',
                'otro_chofer' => 'Juan eduardo Fernandez',
                'otro_proveedor' => NULL,
                'otro_vehiculo' => '75HGAY',
                'planta_destino_id' => 2,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'INDUSTRIAL',
                'updated_at' => '2025-11-12 17:27:31',
                'vehiculo_id' => NULL,
                'viaje_id' => 110,
            ),
            1 => 
            array (
                'cantidad_litros' => 108000,
                'cantidad_recibida' => NULL,
                'cisterna' => NULL,
                'created_at' => '2025-11-18 16:27:13',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2025-11-19',
                'flete' => 1,
                'id' => 21,
                'observaciones' => 'FLETE REALIZADO POR TRANSPORTES URDANETA MARTINEZ ARGENIS',
                'otro_ayudante' => 'N/A',
                'otro_chofer' => 'ENRIQUE GONZALEZ',
                'otro_proveedor' => NULL,
                'otro_vehiculo' => 'A78AM7J',
                'planta_destino_id' => 6,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'INDUSTRIAL',
                'updated_at' => '2025-11-18 16:27:13',
                'vehiculo_id' => NULL,
                'viaje_id' => 130,
            ),
            2 => 
            array (
                'cantidad_litros' => 40500,
                'cantidad_recibida' => NULL,
                'cisterna' => NULL,
                'created_at' => '2025-11-18 18:55:08',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2025-11-19',
                'flete' => 1,
                'id' => 22,
                'observaciones' => 'Flete trasporte y suministros García',
                'otro_ayudante' => 'N/A',
                'otro_chofer' => 'Richard Marin',
                'otro_proveedor' => NULL,
                'otro_vehiculo' => 'A64BN0D-13IAAV',
                'planta_destino_id' => 2,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'INDUSTRIAL',
                'updated_at' => '2025-11-18 18:55:08',
                'vehiculo_id' => NULL,
                'viaje_id' => 133,
            ),
            3 => 
            array (
                'cantidad_litros' => 36000,
                'cantidad_recibida' => NULL,
                'cisterna' => 17,
                'created_at' => '2025-11-19 11:04:07',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2025-11-19',
                'flete' => 0,
                'id' => 23,
                'observaciones' => NULL,
                'otro_ayudante' => NULL,
                'otro_chofer' => NULL,
                'otro_proveedor' => NULL,
                'otro_vehiculo' => NULL,
                'planta_destino_id' => 1,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'M.G.O.',
                'updated_at' => '2025-11-19 11:04:07',
                'vehiculo_id' => 45,
                'viaje_id' => 134,
            ),
            4 => 
            array (
                'cantidad_litros' => 40500,
                'cantidad_recibida' => NULL,
                'cisterna' => NULL,
                'created_at' => '2025-11-20 22:05:34',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2025-11-21',
                'flete' => 0,
                'id' => 24,
                'observaciones' => 'Cliente: Impordiesel
Código Sap: 508924
Transporte y Suministros García',
                'otro_ayudante' => 'N/A',
                'otro_chofer' => 'Luis Rodríguez',
                'otro_proveedor' => NULL,
                'otro_vehiculo' => 'A71AK61-13IAAV',
                'planta_destino_id' => 2,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'INDUSTRIAL',
                'updated_at' => '2025-11-20 22:05:34',
                'vehiculo_id' => NULL,
                'viaje_id' => 148,
            ),
            5 => 
            array (
                'cantidad_litros' => 38000,
                'cantidad_recibida' => NULL,
                'cisterna' => 51,
                'created_at' => '2025-11-21 13:23:33',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2025-11-22',
                'flete' => 0,
                'id' => 25,
                'observaciones' => 'Código SAP 508924
Cliente: Distribuidora Impordiesel',
                'otro_ayudante' => NULL,
                'otro_chofer' => NULL,
                'otro_proveedor' => NULL,
                'otro_vehiculo' => NULL,
                'planta_destino_id' => 1,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'M.G.O.',
                'updated_at' => '2025-11-21 13:23:33',
                'vehiculo_id' => 30,
                'viaje_id' => 149,
            ),
            6 => 
            array (
                'cantidad_litros' => 38000,
                'cantidad_recibida' => NULL,
                'cisterna' => 51,
                'created_at' => '2025-11-25 16:47:10',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2025-11-26',
                'flete' => 0,
                'id' => 26,
                'observaciones' => 'CARGA MAÑANA MGO PLANTA GUATIRE',
                'otro_ayudante' => NULL,
                'otro_chofer' => NULL,
                'otro_proveedor' => NULL,
                'otro_vehiculo' => NULL,
                'planta_destino_id' => 1,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'M.G.O.',
                'updated_at' => '2025-11-25 16:47:10',
                'vehiculo_id' => 30,
                'viaje_id' => 161,
            ),
            7 => 
            array (
                'cantidad_litros' => 38000,
                'cantidad_recibida' => NULL,
                'cisterna' => 51,
                'created_at' => '2025-11-26 11:42:02',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2025-11-27',
                'flete' => 0,
                'id' => 27,
                'observaciones' => 'CODIGO SAP 503050',
                'otro_ayudante' => NULL,
                'otro_chofer' => NULL,
                'otro_proveedor' => NULL,
                'otro_vehiculo' => NULL,
                'planta_destino_id' => 7,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'INDUSTRIAL',
                'updated_at' => '2025-11-26 11:42:02',
                'vehiculo_id' => 30,
                'viaje_id' => 162,
            ),
            8 => 
            array (
                'cantidad_litros' => 38000,
                'cantidad_recibida' => NULL,
                'cisterna' => 51,
                'created_at' => '2025-11-28 15:31:50',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2025-11-29',
                'flete' => 0,
                'id' => 28,
                'observaciones' => 'SAP-508924',
                'otro_ayudante' => NULL,
                'otro_chofer' => NULL,
                'otro_proveedor' => NULL,
                'otro_vehiculo' => NULL,
                'planta_destino_id' => 2,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'M.G.O.',
                'updated_at' => '2025-11-28 15:31:50',
                'vehiculo_id' => 30,
                'viaje_id' => 172,
            ),
            9 => 
            array (
                'cantidad_litros' => 38000,
                'cantidad_recibida' => NULL,
                'cisterna' => NULL,
                'created_at' => '2025-12-02 10:14:01',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2025-12-02',
                'flete' => 0,
                'id' => 29,
                'observaciones' => 'RUTA: GUARAGUAO-PTO. ORDAZ
TRANSPORTE: TRASPORTE Y SUMINISTROS GRACIA
SAP: 508924',
                'otro_ayudante' => 'N/A',
                'otro_chofer' => 'ANDRES SALAZAR',
                'otro_proveedor' => NULL,
                'otro_vehiculo' => '74GDBB-A12BO4M',
                'planta_destino_id' => 2,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'INDUSTRIAL',
                'updated_at' => '2025-12-02 10:14:01',
                'vehiculo_id' => NULL,
                'viaje_id' => 184,
            ),
            10 => 
            array (
                'cantidad_litros' => 38000,
                'cantidad_recibida' => NULL,
                'cisterna' => NULL,
                'created_at' => '2025-12-02 10:34:34',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2025-12-02',
                'flete' => 0,
                'id' => 30,
                'observaciones' => 'RUTA: GUARAGUAO-PTO. ORDAZ
TRANSPORTE: TRASPORTE Y SUMINISTROS GRACIA
SAP: 508924',
                'otro_ayudante' => 'N/A',
                'otro_chofer' => 'ANDRES SALAZAR',
                'otro_proveedor' => NULL,
                'otro_vehiculo' => '74GDBB-A12BO4M',
                'planta_destino_id' => 2,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'INDUSTRIAL',
                'updated_at' => '2025-12-02 10:34:34',
                'vehiculo_id' => NULL,
                'viaje_id' => 185,
            ),
            11 => 
            array (
                'cantidad_litros' => 10800,
                'cantidad_recibida' => NULL,
                'cisterna' => NULL,
                'created_at' => '2025-12-03 16:58:44',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2025-12-04',
                'flete' => 0,
                'id' => 31,
                'observaciones' => 'TRANSPORTE: TRANSPORTE URDANETA MARTINEZ ARGENIS
CODIGO SAP: 508924',
                'otro_ayudante' => 'N/A',
                'otro_chofer' => 'ENRIQUE GONZALEZ',
                'otro_proveedor' => NULL,
                'otro_vehiculo' => 'A78AM7J',
                'planta_destino_id' => 6,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'INDUSTRIAL',
                'updated_at' => '2025-12-03 16:58:44',
                'vehiculo_id' => NULL,
                'viaje_id' => 196,
            ),
            12 => 
            array (
                'cantidad_litros' => 38000,
                'cantidad_recibida' => NULL,
                'cisterna' => NULL,
                'created_at' => '2025-12-09 12:21:01',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2025-12-05',
                'flete' => 0,
                'id' => 32,
                'observaciones' => NULL,
                'otro_ayudante' => NULL,
                'otro_chofer' => 'JESUS RONDON',
                'otro_proveedor' => NULL,
                'otro_vehiculo' => '42NNAC',
                'planta_destino_id' => 2,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'M.G.O.',
                'updated_at' => '2025-12-09 12:21:01',
                'vehiculo_id' => NULL,
                'viaje_id' => 210,
            ),
            13 => 
            array (
                'cantidad_litros' => 38000,
                'cantidad_recibida' => NULL,
                'cisterna' => 51,
                'created_at' => '2025-12-09 12:30:31',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2025-12-04',
                'flete' => 0,
                'id' => 33,
                'observaciones' => NULL,
                'otro_ayudante' => NULL,
                'otro_chofer' => NULL,
                'otro_proveedor' => NULL,
                'otro_vehiculo' => NULL,
                'planta_destino_id' => 2,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'M.G.O.',
                'updated_at' => '2025-12-09 12:30:31',
                'vehiculo_id' => 30,
                'viaje_id' => 212,
            ),
            14 => 
            array (
                'cantidad_litros' => 38000,
                'cantidad_recibida' => NULL,
                'cisterna' => NULL,
                'created_at' => '2025-12-09 12:42:15',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2025-12-03',
                'flete' => 0,
                'id' => 34,
                'observaciones' => NULL,
                'otro_ayudante' => NULL,
                'otro_chofer' => 'JAIRO ROJAS',
                'otro_proveedor' => NULL,
                'otro_vehiculo' => 'A43A05L',
                'planta_destino_id' => 2,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'M.G.O.',
                'updated_at' => '2025-12-09 12:42:15',
                'vehiculo_id' => NULL,
                'viaje_id' => 213,
            ),
            15 => 
            array (
                'cantidad_litros' => 38000,
                'cantidad_recibida' => NULL,
                'cisterna' => 51,
                'created_at' => '2025-12-11 10:10:48',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2025-12-11',
                'flete' => 0,
                'id' => 35,
                'observaciones' => 'CARGA IMPORDIESEL',
                'otro_ayudante' => NULL,
                'otro_chofer' => NULL,
                'otro_proveedor' => NULL,
                'otro_vehiculo' => NULL,
                'planta_destino_id' => 1,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'INDUSTRIAL',
                'updated_at' => '2025-12-11 10:10:49',
                'vehiculo_id' => 45,
                'viaje_id' => 222,
            ),
            16 => 
            array (
                'cantidad_litros' => 36000,
                'cantidad_recibida' => NULL,
                'cisterna' => 17,
                'created_at' => '2025-12-30 00:07:49',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2025-12-30',
                'flete' => 0,
                'id' => 36,
                'observaciones' => 'Flete Diprodepe
Rura: ccs-guatire-ccs',
                'otro_ayudante' => NULL,
                'otro_chofer' => NULL,
                'otro_proveedor' => NULL,
                'otro_vehiculo' => NULL,
                'planta_destino_id' => 1,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'INDUSTRIAL',
                'updated_at' => '2025-12-30 00:07:49',
                'vehiculo_id' => 30,
                'viaje_id' => 284,
            ),
            17 => 
            array (
                'cantidad_litros' => 38000,
                'cantidad_recibida' => NULL,
                'cisterna' => 17,
                'created_at' => '2026-01-03 23:05:25',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2026-01-03',
                'flete' => 0,
                'id' => 37,
                'observaciones' => 'Carga doble 
Ccs- Guatire',
                'otro_ayudante' => NULL,
                'otro_chofer' => NULL,
                'otro_proveedor' => NULL,
                'otro_vehiculo' => NULL,
                'planta_destino_id' => 1,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'INDUSTRIAL',
                'updated_at' => '2026-01-03 23:05:26',
                'vehiculo_id' => 30,
                'viaje_id' => 288,
            ),
            18 => 
            array (
                'cantidad_litros' => 36000,
                'cantidad_recibida' => NULL,
                'cisterna' => 17,
                'created_at' => '2026-01-03 23:06:19',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2026-01-03',
                'flete' => 0,
                'id' => 38,
                'observaciones' => 'Carga doble 
Ccs- Guatire',
                'otro_ayudante' => NULL,
                'otro_chofer' => NULL,
                'otro_proveedor' => NULL,
                'otro_vehiculo' => NULL,
                'planta_destino_id' => 1,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'INDUSTRIAL',
                'updated_at' => '2026-01-03 23:06:19',
                'vehiculo_id' => 30,
                'viaje_id' => 289,
            ),
            19 => 
            array (
                'cantidad_litros' => 38000,
                'cantidad_recibida' => NULL,
                'cisterna' => NULL,
                'created_at' => '2026-01-12 11:50:35',
                'estatus' => 'PROGRAMADO',
                'fecha' => '2026-01-12',
                'flete' => 0,
                'id' => 39,
                'observaciones' => 'RUTA GUARAGUAO-CCS',
                'otro_ayudante' => NULL,
                'otro_chofer' => 'MAURO RIFFI',
                'otro_proveedor' => NULL,
                'otro_vehiculo' => 'A87BN8D-30CIAC',
                'planta_destino_id' => 2,
                'proveedor_id' => 1,
                'sap' => NULL,
                'tipo' => 'INDUSTRIAL',
                'updated_at' => '2026-01-12 11:50:35',
                'vehiculo_id' => NULL,
                'viaje_id' => 309,
            ),
        ));
        
        
    }
}