<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class GuiasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('guias')->delete();
        
        \DB::table('guias')->insert(array (
            0 => 
            array (
                'buque' => 'A31AT1M',
                'buque_id' => NULL,
                'cantidad' => 12000,
                'cedula' => 'V 24.058.155',
                'cisterna' => 'N/A',
                'cliente' => 'FARMATODO - CENDIS',
                'cliente_id' => NULL,
                'conductor' => 'Yhender Bostanio',
                'contacto' => NULL,
                'created_at' => '2025-12-15 15:01:33',
                'direccion' => 'N/A',
                'email' => NULL,
                'id' => 1,
                'muelle' => NULL,
                'muelle_id' => NULL,
                'numero_guia' => 1,
                'observaciones' => NULL,
                'precintos' => NULL,
                'producto' => 'MARINE GASOIL M.G.O',
                'rif' => 'N/A',
                'ruta' => 'CHARALLAVE',
                'telefono' => NULL,
                'unidad' => 'N° 31',
                'updated_at' => '2025-12-15 15:01:33',
                'viaje_id' => 230,
            ),
            1 => 
            array (
                'buque' => NULL,
                'buque_id' => NULL,
                'cantidad' => 12000,
                'cedula' => 'V10.690.824',
                'cisterna' => 'N/A',
                'cliente' => 'Bolivariana De Puertos Bolipuertos Sa',
                'cliente_id' => NULL,
                'conductor' => 'Mariano Hernandez',
                'contacto' => NULL,
                'created_at' => '2025-12-15 16:02:03',
                'direccion' => 'Av Veracruz Con Calle Orinoco Edf Torre 2Rr Piso 6 Of Sn Urb Las Mercedes',
                'email' => NULL,
                'id' => 2,
                'muelle' => NULL,
                'muelle_id' => NULL,
                'numero_guia' => 2,
                'observaciones' => NULL,
                'precintos' => NULL,
                'producto' => 'MARINE GASOIL M.G.O',
                'rif' => 'G200163151',
                'ruta' => 'LA GRAN CARACAS',
                'telefono' => NULL,
                'unidad' => 'N° 31',
                'updated_at' => '2025-12-15 16:02:03',
                'viaje_id' => 236,
            ),
            2 => 
            array (
                'buque' => 'PRUEBA',
                'buque_id' => NULL,
                'cantidad' => 20000,
                'cedula' => 'V10.690.824',
                'cisterna' => 'GAH732',
                'cliente' => 'Bolivariana De Puertos Bolipuertos Sa [GUAMACHE]',
                'cliente_id' => NULL,
                'conductor' => 'Mariano Hernandez',
                'contacto' => NULL,
                'created_at' => '2025-12-17 09:50:04',
                'direccion' => 'N/A',
                'email' => NULL,
                'id' => 3,
                'muelle' => NULL,
                'muelle_id' => NULL,
                'numero_guia' => 3,
                'observaciones' => NULL,
                'precintos' => '672637 21983928 283928',
                'producto' => 'MARINE GASOIL M.G.O',
                'rif' => 'G200163151',
                'ruta' => 'ANZOATEGUI',
                'telefono' => NULL,
                'unidad' => 'N° 20',
                'updated_at' => '2025-12-17 18:38:22',
                'viaje_id' => 246,
            ),
            3 => 
            array (
                'buque' => NULL,
                'buque_id' => NULL,
                'cantidad' => 5500,
                'cedula' => 'V 24.058.155',
                'cisterna' => 'N/A',
                'cliente' => 'CLUB PUERTO AZUL',
                'cliente_id' => NULL,
                'conductor' => 'Yhender Bostanio',
                'contacto' => NULL,
                'created_at' => '2025-12-17 13:42:16',
                'direccion' => 'N/A',
                'email' => NULL,
                'id' => 4,
                'muelle' => NULL,
                'muelle_id' => NULL,
                'numero_guia' => 4,
                'observaciones' => NULL,
                'precintos' => NULL,
                'producto' => 'MARINE GASOIL M.G.O',
                'rif' => 'N/A',
                'ruta' => 'LA GUAIRA',
                'telefono' => NULL,
                'unidad' => 'N° 15',
                'updated_at' => '2025-12-17 13:42:16',
                'viaje_id' => 244,
            ),
            4 => 
            array (
                'buque' => NULL,
                'buque_id' => NULL,
                'cantidad' => 38000,
                'cedula' => '22.500.458',
                'cisterna' => 'N/A',
                'cliente' => 'BOLIVARIAN DE PUERTOS -PUERTO LA GUAIRA',
                'cliente_id' => NULL,
                'conductor' => 'Javier Torres',
                'contacto' => NULL,
                'created_at' => '2025-12-19 10:32:13',
                'direccion' => 'N/A',
                'email' => NULL,
                'id' => 5,
                'muelle' => NULL,
                'muelle_id' => NULL,
                'numero_guia' => 5,
                'observaciones' => NULL,
                'precintos' => NULL,
                'producto' => 'MARINE GASOIL M.G.O',
                'rif' => 'N/A',
                'ruta' => 'LA GUAIRA',
                'telefono' => NULL,
                'unidad' => 'N° 37',
                'updated_at' => '2025-12-19 10:32:13',
                'viaje_id' => 247,
            ),
            5 => 
            array (
                'buque' => NULL,
                'buque_id' => NULL,
                'cantidad' => 5000,
                'cedula' => '13.114.214',
                'cisterna' => 'N/A',
                'cliente' => 'GLOBALAGRO',
                'cliente_id' => NULL,
                'conductor' => 'Rodolfo Padron',
                'contacto' => NULL,
                'created_at' => '2025-12-19 11:30:15',
                'direccion' => 'N/A',
                'email' => NULL,
                'id' => 6,
                'muelle' => NULL,
                'muelle_id' => NULL,
                'numero_guia' => 6,
                'observaciones' => NULL,
                'precintos' => NULL,
                'producto' => 'MARINE GASOIL M.G.O',
                'rif' => 'N/A',
                'ruta' => 'VALENCIA',
                'telefono' => NULL,
                'unidad' => 'N° 62',
                'updated_at' => '2025-12-19 11:30:15',
                'viaje_id' => 250,
            ),
            6 => 
            array (
                'buque' => NULL,
                'buque_id' => NULL,
                'cantidad' => 7000,
                'cedula' => 'V10.690.824',
                'cisterna' => 'N/A',
                'cliente' => 'MULTIEVENTOS A33- LOS CORTIJOS',
                'cliente_id' => NULL,
                'conductor' => 'Mariano Hernandez',
                'contacto' => NULL,
                'created_at' => '2025-12-19 15:24:51',
                'direccion' => 'N/A',
                'email' => NULL,
                'id' => 7,
                'muelle' => NULL,
                'muelle_id' => NULL,
                'numero_guia' => 7,
                'observaciones' => NULL,
                'precintos' => NULL,
                'producto' => 'MARINE GASOIL M.G.O',
                'rif' => 'N/A',
                'ruta' => 'LA GRAN CARACAS',
                'telefono' => NULL,
                'unidad' => 'N° 31',
                'updated_at' => '2025-12-19 15:24:51',
                'viaje_id' => 253,
            ),
            7 => 
            array (
                'buque' => 'N/A',
                'buque_id' => NULL,
                'cantidad' => 20800,
                'cedula' => '13.114.214',
                'cisterna' => 'N/A',
                'cliente' => 'MINISTERIO  AGRICULTURA Y TIERRA',
                'cliente_id' => NULL,
                'conductor' => 'Rodolfo Padron',
                'contacto' => NULL,
                'created_at' => '2025-12-22 09:09:51',
                'direccion' => 'N/A',
                'email' => NULL,
                'id' => 8,
                'muelle' => NULL,
                'muelle_id' => NULL,
                'numero_guia' => 8,
                'observaciones' => NULL,
                'precintos' => NULL,
                'producto' => 'MARINE GASOIL M.G.O',
                'rif' => 'N/A',
                'ruta' => 'LA GRAN CARACAS',
                'telefono' => NULL,
                'unidad' => 'N° 20',
                'updated_at' => '2025-12-22 10:12:03',
                'viaje_id' => 262,
            ),
            8 => 
            array (
                'buque' => NULL,
                'buque_id' => NULL,
                'cantidad' => 10000,
                'cedula' => 'V 24.058.155',
                'cisterna' => 'N/A',
                'cliente' => 'INVERSIONES FONTANOL',
                'cliente_id' => NULL,
                'conductor' => 'Yhender Bostanio',
                'contacto' => NULL,
                'created_at' => '2025-12-22 10:43:58',
                'direccion' => 'N/A',
                'email' => NULL,
                'id' => 9,
                'muelle' => NULL,
                'muelle_id' => NULL,
                'numero_guia' => 9,
                'observaciones' => NULL,
                'precintos' => NULL,
                'producto' => 'MARINE GASOIL M.G.O',
                'rif' => 'N/A',
                'ruta' => 'LA GRAN CARACAS',
                'telefono' => NULL,
                'unidad' => 'N° 31',
                'updated_at' => '2025-12-22 10:43:58',
                'viaje_id' => 264,
            ),
            9 => 
            array (
                'buque' => NULL,
                'buque_id' => NULL,
                'cantidad' => 36000,
                'cedula' => 'V10.690.824',
                'cisterna' => 'N/A',
                'cliente' => 'NESTLE VENEZUELA - FLE',
                'cliente_id' => NULL,
                'conductor' => 'Mariano Hernandez',
                'contacto' => NULL,
                'created_at' => '2025-12-22 11:01:14',
                'direccion' => 'N/A',
                'email' => NULL,
                'id' => 10,
                'muelle' => NULL,
                'muelle_id' => NULL,
                'numero_guia' => 10,
                'observaciones' => NULL,
                'precintos' => NULL,
                'producto' => 'MARINE GASOIL M.G.O',
                'rif' => 'N/A',
                'ruta' => 'MARACAY',
                'telefono' => NULL,
                'unidad' => 'N° 37',
                'updated_at' => '2025-12-22 11:01:14',
                'viaje_id' => 263,
            ),
            10 => 
            array (
                'buque' => 'N/A',
                'buque_id' => NULL,
                'cantidad' => 5000,
                'cedula' => '15.870.536',
                'cisterna' => 'N/A',
                'cliente' => 'WORLD SEA LOGISTICS SERVICE, C.A.',
                'cliente_id' => NULL,
                'conductor' => 'Brenitte Silva',
                'contacto' => NULL,
                'created_at' => '2025-12-22 17:38:28',
                'direccion' => 'CALLE PUERTO CABELLO, EDIF. BOLIVARIANA DE PUERTOS',
                'email' => NULL,
                'id' => 11,
                'muelle' => 'Bauxilum',
                'muelle_id' => 15,
                'numero_guia' => 11,
                'observaciones' => NULL,
                'precintos' => NULL,
                'producto' => 'MARINE GASOIL M.G.O',
                'rif' => '501398275',
                'ruta' => 'PTO ORDAZ',
                'telefono' => NULL,
                'unidad' => 'N° 31',
                'updated_at' => '2025-12-22 17:38:28',
                'viaje_id' => 267,
            ),
            11 => 
            array (
                'buque' => 'NvoBuque',
                'buque_id' => 1,
                'cantidad' => 7000,
                'cedula' => '15.870.536',
                'cisterna' => 'N/A',
                'cliente' => 'WORLD SEA LOGISTICS SERVICE, C.A.',
                'cliente_id' => NULL,
                'conductor' => 'Brenitte Silva',
                'contacto' => ' ',
                'created_at' => '2025-12-22 17:42:11',
                'direccion' => 'CALLE PUERTO CABELLO, EDIF. BOLIVARIANA DE PUERTOS',
                'email' => 'disnalogistic@gmail.com',
                'id' => 12,
                'muelle' => 'Bauxilum',
                'muelle_id' => 15,
                'numero_guia' => 12,
                'observaciones' => NULL,
                'precintos' => NULL,
                'producto' => 'MARINE GASOIL M.G.O',
                'rif' => '501398275',
                'ruta' => 'PTO ORDAZ',
                'telefono' => '04243484776',
                'unidad' => 'N° 89',
                'updated_at' => '2025-12-23 11:31:36',
                'viaje_id' => 268,
            ),
            12 => 
            array (
                'buque' => NULL,
                'buque_id' => NULL,
                'cantidad' => 1200,
                'cedula' => 'V10.690.824',
                'cisterna' => 'N/A',
                'cliente' => 'REP. INVERSORA SIERRA NOVIEMBRE',
                'cliente_id' => NULL,
                'conductor' => 'Mariano Hernandez',
                'contacto' => NULL,
                'created_at' => '2025-12-29 09:19:07',
                'direccion' => 'N/A',
                'email' => NULL,
                'id' => 13,
                'muelle' => NULL,
                'muelle_id' => NULL,
                'numero_guia' => 13,
                'observaciones' => NULL,
                'precintos' => NULL,
                'producto' => 'MARINE GASOIL M.G.O',
                'rif' => 'N/A',
                'ruta' => 'LA GUAIRA',
                'telefono' => NULL,
                'unidad' => 'N° 47',
                'updated_at' => '2025-12-29 09:19:07',
                'viaje_id' => 277,
            ),
            13 => 
            array (
                'buque' => NULL,
                'buque_id' => NULL,
                'cantidad' => 20000,
                'cedula' => 'V10.690.824',
                'cisterna' => 'N/A',
                'cliente' => 'Bolivariana De Puertos Bolipuertos Sa',
                'cliente_id' => 370,
                'conductor' => 'Mariano Hernandez',
                'contacto' => NULL,
                'created_at' => '2026-01-02 10:01:27',
                'direccion' => 'Terminal Especializado De Contenedores Puerto De La Guaira Estado La Guaira',
                'email' => NULL,
                'id' => 14,
                'muelle' => NULL,
                'muelle_id' => NULL,
                'numero_guia' => 14,
                'observaciones' => NULL,
                'precintos' => NULL,
                'producto' => 'MARINE GASOIL M.G.O',
                'rif' => 'G200163151',
                'ruta' => 'LA GUAIRA',
                'telefono' => NULL,
                'unidad' => 'N° 20',
                'updated_at' => '2026-01-02 10:01:27',
                'viaje_id' => 287,
            ),
            14 => 
            array (
                'buque' => NULL,
                'buque_id' => NULL,
                'cantidad' => 700,
                'cedula' => 'V10.690.824',
                'cisterna' => 'N/A',
                'cliente' => 'EMBARCACIÓN MACAMAR',
                'cliente_id' => NULL,
                'conductor' => 'MARIANO HERNANDEZ',
                'contacto' => NULL,
                'created_at' => '2026-01-19 12:41:37',
                'direccion' => 'N/A',
                'email' => NULL,
                'id' => 15,
                'muelle' => NULL,
                'muelle_id' => NULL,
                'numero_guia' => 15,
                'observaciones' => NULL,
                'precintos' => NULL,
                'producto' => 'MARINE GASOIL M.G.O',
                'rif' => 'N/A',
                'ruta' => 'LA GRAN CARACAS',
                'telefono' => NULL,
                'unidad' => 'N° 47',
                'updated_at' => '2026-01-19 12:41:37',
                'viaje_id' => 324,
            ),
        ));
        
        
    }
}