<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PedidosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('pedidos')->delete();
        
        \DB::table('pedidos')->insert(array (
            0 => 
            array (
                'calificacion' => 5,
                'cantidad_aprobada' => '1000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => NULL,
                'cliente_id' => 1,
                'comentario_calificacion' => 'Todo ok',
                'created_at' => '2025-09-01 14:23:40',
                'deposito_id' => 6,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-01 14:24:57',
                'fecha_completado' => '2025-09-01 14:27:12',
                'fecha_solicitud' => '2025-09-01 14:23:40',
                'id' => 1,
                'observaciones' => 'prueba',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-01 14:27:27',
                'vehiculo_id' => 28,
            ),
            1 => 
            array (
                'calificacion' => 4,
                'cantidad_aprobada' => '1200.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1200.00',
                'chofer_id' => NULL,
                'cliente_id' => 1,
                'comentario_calificacion' => 'Prueba.',
                'created_at' => '2025-09-01 14:33:10',
                'deposito_id' => 5,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-01 14:33:50',
                'fecha_completado' => '2025-09-01 14:37:17',
                'fecha_solicitud' => '2025-09-01 14:33:10',
                'id' => 2,
                'observaciones' => 'Compra de prueba',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-01 14:38:08',
                'vehiculo_id' => 16,
            ),
            2 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '200.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '200.00',
                'chofer_id' => NULL,
                'cliente_id' => 2,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-03 07:18:58',
                'deposito_id' => NULL,
                'estado' => 'cancelado',
                'fecha_aprobacion' => '2025-09-03 07:18:58',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-09-03 07:18:58',
                'id' => 6,
                'observaciones' => 'Pedido creado y aprobado directamente por el administrador.',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-16 15:40:08',
                'vehiculo_id' => NULL,
            ),
            3 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '150.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '150.00',
                'chofer_id' => NULL,
                'cliente_id' => 8,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-03 07:23:18',
                'deposito_id' => NULL,
                'estado' => 'aprobado',
                'fecha_aprobacion' => '2025-09-03 07:23:18',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-09-03 07:23:18',
                'id' => 7,
                'observaciones' => 'Pedido creado y aprobado directamente por el administrador.',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-03 07:23:18',
                'vehiculo_id' => NULL,
            ),
            4 => 
            array (
                'calificacion' => 5,
                'cantidad_aprobada' => '300.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '300.00',
                'chofer_id' => NULL,
                'cliente_id' => 1,
                'comentario_calificacion' => 'muy bien',
                'created_at' => '2025-09-03 13:47:23',
                'deposito_id' => 3,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-03 14:13:56',
                'fecha_completado' => '2025-09-03 18:33:15',
                'fecha_solicitud' => '2025-09-03 13:47:23',
                'id' => 8,
                'observaciones' => 'Test',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-03 18:33:15',
                'vehiculo_id' => 30,
            ),
            5 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '500.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '500.00',
                'chofer_id' => NULL,
                'cliente_id' => 5,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-03 15:07:49',
                'deposito_id' => NULL,
                'estado' => 'aprobado',
                'fecha_aprobacion' => '2025-09-03 15:07:49',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-09-03 15:07:49',
                'id' => 9,
                'observaciones' => 'Pedido creado y aprobado directamente por el administrador.',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-03 15:07:49',
                'vehiculo_id' => NULL,
            ),
            6 => 
            array (
                'calificacion' => 5,
                'cantidad_aprobada' => '200.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '200.00',
                'chofer_id' => NULL,
                'cliente_id' => 1,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-03 15:23:38',
                'deposito_id' => 4,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-03 15:27:07',
                'fecha_completado' => '2025-09-03 15:59:22',
                'fecha_solicitud' => '2025-09-03 15:23:38',
                'id' => 10,
                'observaciones' => 'a la brevedad',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-03 16:00:20',
                'vehiculo_id' => 17,
            ),
            7 => 
            array (
                'calificacion' => 5,
                'cantidad_aprobada' => '1000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => NULL,
                'cliente_id' => 1,
                'comentario_calificacion' => 'muy bien',
                'created_at' => '2025-09-03 15:32:13',
                'deposito_id' => 5,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-03 15:32:59',
                'fecha_completado' => '2025-09-03 18:32:14',
                'fecha_solicitud' => '2025-09-03 15:32:13',
                'id' => 11,
                'observaciones' => 'rapido',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-03 18:32:14',
                'vehiculo_id' => 24,
            ),
            8 => 
            array (
                'calificacion' => 5,
                'cantidad_aprobada' => '2000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '2000.00',
                'chofer_id' => NULL,
                'cliente_id' => 352,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-08 16:14:26',
                'deposito_id' => 4,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-08 16:14:50',
                'fecha_completado' => '2025-09-08 16:17:29',
                'fecha_solicitud' => '2025-09-08 16:14:26',
                'id' => 12,
                'observaciones' => 'rapido por  favor',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-08 16:17:29',
                'vehiculo_id' => 14,
            ),
            9 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '1000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => NULL,
                'cliente_id' => 352,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-08 16:21:32',
                'deposito_id' => 7,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-08 16:21:43',
                'fecha_completado' => '2025-09-08 19:11:36',
                'fecha_solicitud' => '2025-09-08 16:21:32',
                'id' => 13,
                'observaciones' => NULL,
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-08 19:11:36',
                'vehiculo_id' => 35,
            ),
            10 => 
            array (
                'calificacion' => 5,
                'cantidad_aprobada' => '6600.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '6600.00',
                'chofer_id' => NULL,
                'cliente_id' => 351,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-08 17:11:59',
                'deposito_id' => 6,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-08 17:12:23',
                'fecha_completado' => '2025-09-08 17:25:20',
                'fecha_solicitud' => '2025-09-08 17:11:59',
                'id' => 14,
                'observaciones' => 'Prueba',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-08 17:25:20',
                'vehiculo_id' => 34,
            ),
            11 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '400.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '400.00',
                'chofer_id' => NULL,
                'cliente_id' => 351,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-08 18:10:12',
                'deposito_id' => 3,
                'estado' => 'en_proceso',
                'fecha_aprobacion' => '2025-09-08 18:11:18',
                'fecha_completado' => '2025-09-08 18:19:16',
                'fecha_solicitud' => '2025-09-08 18:10:12',
                'id' => 15,
                'observaciones' => 'pedir prueba nueva',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-08 18:19:16',
                'vehiculo_id' => 36,
            ),
            12 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '400.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '400.00',
                'chofer_id' => NULL,
                'cliente_id' => 351,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-08 18:12:34',
                'deposito_id' => 4,
                'estado' => 'en_proceso',
                'fecha_aprobacion' => '2025-09-08 18:19:32',
                'fecha_completado' => '2025-09-11 13:20:18',
                'fecha_solicitud' => '2025-09-08 18:12:34',
                'id' => 16,
                'observaciones' => 'pgos',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-11 13:20:18',
                'vehiculo_id' => 30,
            ),
            13 => 
            array (
                'calificacion' => 4,
                'cantidad_aprobada' => '1000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => NULL,
                'cliente_id' => 349,
                'comentario_calificacion' => 'muy bien',
                'created_at' => '2025-09-08 18:18:18',
                'deposito_id' => 5,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-08 18:18:36',
                'fecha_completado' => '2025-09-08 18:19:21',
                'fecha_solicitud' => '2025-09-08 18:18:18',
                'id' => 17,
                'observaciones' => 'prueba de pedido benjamin',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-08 18:19:53',
                'vehiculo_id' => 25,
            ),
            14 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '2000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '2000.00',
                'chofer_id' => NULL,
                'cliente_id' => 352,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-08 18:19:44',
                'deposito_id' => NULL,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-08 19:12:50',
                'fecha_completado' => '2025-09-08 19:15:12',
                'fecha_solicitud' => '2025-09-08 18:19:44',
                'id' => 18,
                'observaciones' => NULL,
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-08 19:15:12',
                'vehiculo_id' => NULL,
            ),
            15 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '1000.00',
                'cantidad_recibida' => '1000.00',
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => NULL,
                'cliente_id' => 352,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-08 19:15:38',
                'deposito_id' => 4,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-08 19:15:48',
                'fecha_completado' => '2025-09-10 13:04:31',
                'fecha_solicitud' => '2025-09-08 19:15:38',
                'id' => 19,
                'observaciones' => NULL,
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-10 13:04:31',
                'vehiculo_id' => 33,
            ),
            16 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '2000.00',
                'cantidad_recibida' => '2000.00',
                'cantidad_solicitada' => '2000.00',
                'chofer_id' => NULL,
                'cliente_id' => 352,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-10 13:03:27',
                'deposito_id' => 3,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-10 13:03:54',
                'fecha_completado' => '2025-09-10 14:27:40',
                'fecha_solicitud' => '2025-09-10 13:03:27',
                'id' => 20,
                'observaciones' => NULL,
                'observaciones_admin' => 'Aprobacion',
                'updated_at' => '2025-09-10 14:27:40',
                'vehiculo_id' => 18,
            ),
            17 => 
            array (
                'calificacion' => 5,
                'cantidad_aprobada' => '2000.00',
                'cantidad_recibida' => '2000.00',
                'cantidad_solicitada' => '2000.00',
                'chofer_id' => NULL,
                'cliente_id' => 352,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-11 13:14:03',
                'deposito_id' => 4,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-11 13:15:45',
                'fecha_completado' => '2025-09-11 13:24:05',
                'fecha_solicitud' => '2025-09-11 13:14:03',
                'id' => 21,
                'observaciones' => NULL,
                'observaciones_admin' => 'Prueba',
                'updated_at' => '2025-09-11 13:24:05',
                'vehiculo_id' => 33,
            ),
            18 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => NULL,
                'cliente_id' => 352,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-12 12:51:59',
                'deposito_id' => NULL,
                'estado' => 'cancelado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-09-12 12:51:59',
                'id' => 22,
                'observaciones' => NULL,
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-12 12:52:39',
                'vehiculo_id' => NULL,
            ),
            19 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '1000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => NULL,
                'cliente_id' => 352,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-12 12:53:42',
                'deposito_id' => NULL,
                'estado' => 'cancelado',
                'fecha_aprobacion' => '2025-09-12 12:54:05',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-09-12 12:53:42',
                'id' => 23,
                'observaciones' => NULL,
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-12 10:01:34',
                'vehiculo_id' => NULL,
            ),
            20 => 
            array (
                'calificacion' => 5,
                'cantidad_aprobada' => '1000.00',
                'cantidad_recibida' => '1000.00',
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => NULL,
                'cliente_id' => 280,
                'comentario_calificacion' => 'Ok',
                'created_at' => '2025-09-16 14:17:24',
                'deposito_id' => 4,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-16 14:18:25',
                'fecha_completado' => '2025-09-16 14:20:51',
                'fecha_solicitud' => '2025-09-16 14:17:24',
                'id' => 24,
                'observaciones' => 'prueba',
                'observaciones_admin' => 'Ok',
                'updated_at' => '2025-09-16 14:20:51',
                'vehiculo_id' => 21,
            ),
            21 => 
            array (
                'calificacion' => 3,
                'cantidad_aprobada' => '2500.00',
                'cantidad_recibida' => '2500.00',
                'cantidad_solicitada' => '2500.00',
                'chofer_id' => NULL,
                'cliente_id' => 321,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-16 15:11:16',
                'deposito_id' => 3,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-16 15:33:49',
                'fecha_completado' => '2025-09-16 15:40:24',
                'fecha_solicitud' => '2025-09-16 15:11:16',
                'id' => 25,
                'observaciones' => 'Prueba Alerts',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-16 15:40:24',
                'vehiculo_id' => 14,
            ),
            22 => 
            array (
                'calificacion' => 4,
                'cantidad_aprobada' => '2000.00',
                'cantidad_recibida' => '2000.00',
                'cantidad_solicitada' => '2000.00',
                'chofer_id' => NULL,
                'cliente_id' => 282,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-16 15:15:29',
                'deposito_id' => 3,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-16 15:33:46',
                'fecha_completado' => '2025-09-16 15:40:37',
                'fecha_solicitud' => '2025-09-16 15:15:29',
                'id' => 26,
                'observaciones' => 'pruebas',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-16 15:40:37',
                'vehiculo_id' => 16,
            ),
            23 => 
            array (
                'calificacion' => 2,
                'cantidad_aprobada' => '1000.00',
                'cantidad_recibida' => '1000.00',
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => NULL,
                'cliente_id' => 284,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-16 15:25:26',
                'deposito_id' => 7,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-16 15:33:43',
                'fecha_completado' => '2025-09-16 15:39:48',
                'fecha_solicitud' => '2025-09-16 15:25:26',
                'id' => 27,
                'observaciones' => NULL,
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-16 15:39:48',
                'vehiculo_id' => 24,
            ),
            24 => 
            array (
                'calificacion' => 5,
                'cantidad_aprobada' => '2000.00',
                'cantidad_recibida' => '2000.00',
                'cantidad_solicitada' => '2000.00',
                'chofer_id' => NULL,
                'cliente_id' => 320,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-16 15:27:41',
                'deposito_id' => 4,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-16 15:33:41',
                'fecha_completado' => '2025-09-16 15:39:35',
                'fecha_solicitud' => '2025-09-16 15:27:41',
                'id' => 28,
                'observaciones' => NULL,
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-16 15:39:35',
                'vehiculo_id' => 17,
            ),
            25 => 
            array (
                'calificacion' => 5,
                'cantidad_aprobada' => '2500.00',
                'cantidad_recibida' => '2500.00',
                'cantidad_solicitada' => '2500.00',
                'chofer_id' => NULL,
                'cliente_id' => 326,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-16 15:30:36',
                'deposito_id' => 5,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-09-16 15:33:38',
                'fecha_completado' => '2025-09-16 15:39:16',
                'fecha_solicitud' => '2025-09-16 15:30:36',
                'id' => 29,
                'observaciones' => NULL,
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-16 15:39:16',
                'vehiculo_id' => 34,
            ),
            26 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '1000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => NULL,
                'cliente_id' => 277,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-17 15:37:55',
                'deposito_id' => 3,
                'estado' => 'en_proceso',
                'fecha_aprobacion' => '2025-09-23 14:07:22',
                'fecha_completado' => '2025-10-17 16:11:50',
                'fecha_solicitud' => '2025-09-17 15:37:55',
                'id' => 30,
                'observaciones' => 's,ddsmx,cm',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-10-17 16:11:50',
                'vehiculo_id' => 18,
            ),
            27 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '1500.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1500.00',
                'chofer_id' => NULL,
                'cliente_id' => 351,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-09-23 11:56:11',
                'deposito_id' => NULL,
                'estado' => 'aprobado',
                'fecha_aprobacion' => '2025-09-23 14:07:12',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-09-23 11:56:11',
                'id' => 31,
                'observaciones' => NULL,
                'observaciones_admin' => NULL,
                'updated_at' => '2025-09-23 14:07:12',
                'vehiculo_id' => NULL,
            ),
            28 => 
            array (
                'calificacion' => 5,
                'cantidad_aprobada' => '1000.00',
                'cantidad_recibida' => '1000.00',
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => NULL,
                'cliente_id' => 349,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-10-16 16:24:08',
                'deposito_id' => 3,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-10-16 16:31:20',
                'fecha_completado' => '2025-10-16 16:34:50',
                'fecha_solicitud' => '2025-10-16 16:24:08',
                'id' => 32,
                'observaciones' => NULL,
                'observaciones_admin' => NULL,
                'updated_at' => '2025-10-16 16:34:50',
                'vehiculo_id' => 16,
            ),
            29 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '5000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '5000.00',
                'chofer_id' => NULL,
                'cliente_id' => 278,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-10-17 15:59:19',
                'deposito_id' => 5,
                'estado' => 'en_proceso',
                'fecha_aprobacion' => '2025-10-17 16:01:57',
                'fecha_completado' => '2025-10-17 16:03:42',
                'fecha_solicitud' => '2025-10-17 15:59:19',
                'id' => 34,
                'observaciones' => 'Prueba',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-10-17 16:03:42',
                'vehiculo_id' => 13,
            ),
            30 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '5000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '5000.00',
                'chofer_id' => NULL,
                'cliente_id' => 2,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-10-17 16:08:15',
                'deposito_id' => 3,
                'estado' => 'en_proceso',
                'fecha_aprobacion' => '2025-10-17 16:10:25',
                'fecha_completado' => '2025-10-17 16:11:21',
                'fecha_solicitud' => '2025-10-17 16:08:15',
                'id' => 35,
                'observaciones' => 'Quiero que el servicio sea más rápido',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-10-17 16:11:21',
                'vehiculo_id' => 17,
            ),
            31 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '1200.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1200.00',
                'chofer_id' => NULL,
                'cliente_id' => 4,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-10-20 07:51:07',
                'deposito_id' => 5,
                'estado' => 'aprobado',
                'fecha_aprobacion' => '2025-10-20 07:51:07',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-10-20 07:51:07',
                'id' => 36,
                'observaciones' => 'Pedido creado y aprobado directamente por el administrador.',
                'observaciones_admin' => 'pedido via telefonica',
                'updated_at' => '2025-10-20 07:51:07',
                'vehiculo_id' => NULL,
            ),
            32 => 
            array (
                'calificacion' => 3,
                'cantidad_aprobada' => '2000.00',
                'cantidad_recibida' => '2000.00',
                'cantidad_solicitada' => '2000.00',
                'chofer_id' => NULL,
                'cliente_id' => 278,
                'comentario_calificacion' => 'B',
                'created_at' => '2025-10-20 12:31:59',
                'deposito_id' => 3,
                'estado' => 'completado',
                'fecha_aprobacion' => '2025-10-20 12:32:49',
                'fecha_completado' => '2025-10-20 12:51:52',
                'fecha_solicitud' => '2025-10-20 12:31:59',
                'id' => 37,
                'observaciones' => 'Pedido de velocidad',
                'observaciones_admin' => 'despachar de inmediato',
                'updated_at' => '2025-10-20 12:51:52',
                'vehiculo_id' => 17,
            ),
            33 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '1000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => NULL,
                'cliente_id' => 348,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-10-24 17:09:24',
                'deposito_id' => 3,
                'estado' => 'en_proceso',
                'fecha_aprobacion' => '2025-10-24 17:09:24',
                'fecha_completado' => '2025-10-24 17:10:03',
                'fecha_solicitud' => '2025-10-24 17:09:24',
                'id' => 38,
                'observaciones' => 'Pedido creado y aprobado directamente por el administrador.',
                'observaciones_admin' => 'prueba',
                'updated_at' => '2025-10-24 17:10:03',
                'vehiculo_id' => 17,
            ),
            34 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => NULL,
                'cliente_id' => 1,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-11-20 12:42:47',
                'deposito_id' => NULL,
                'estado' => 'rechazado',
                'fecha_aprobacion' => '2025-12-09 16:03:32',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-11-21 01:00:00',
                'id' => 39,
                'observaciones' => 'Prueba',
                'observaciones_admin' => 'no',
                'updated_at' => '2025-12-09 16:03:32',
                'vehiculo_id' => NULL,
            ),
            35 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '30000.00',
                'chofer_id' => 11,
                'cliente_id' => 372,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-03 16:23:23',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-04 15:23:00',
                'id' => 45,
                'observaciones' => 'Pedido generado desde la planificacion: Bolivariana De Puertos Bolipuertos Sa',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-03 16:23:23',
                'vehiculo_id' => 45,
            ),
            36 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '5000.00',
                'chofer_id' => 3,
                'cliente_id' => 304,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-03 16:30:32',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-04 15:29:00',
                'id' => 46,
                'observaciones' => 'Pedido generado desde la planificacion: Nestle De Venzuela Sa Sede Od Maracay',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-03 16:30:32',
                'vehiculo_id' => 16,
            ),
            37 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '5000.00',
                'chofer_id' => 3,
                'cliente_id' => 305,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-03 16:30:35',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-04 15:29:00',
                'id' => 47,
                'observaciones' => 'Pedido generado desde la planificacion: Nestle De Venezuela Sede La Encrucijada',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-03 16:30:35',
                'vehiculo_id' => 16,
            ),
            38 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '4000.00',
                'chofer_id' => 10,
                'cliente_id' => 27,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-03 16:34:28',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-04 15:34:00',
                'id' => 48,
                'observaciones' => 'Pedido generado desde la planificacion: INVERSIONES FONTANOL',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-03 16:34:28',
                'vehiculo_id' => 13,
            ),
            39 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '4000.00',
                'chofer_id' => 10,
                'cliente_id' => 27,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-03 16:34:30',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-04 15:34:00',
                'id' => 49,
                'observaciones' => 'Pedido generado desde la planificacion: INVERSIONES FONTANOL',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-03 16:34:30',
                'vehiculo_id' => 13,
            ),
            40 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '30000.00',
                'chofer_id' => 11,
                'cliente_id' => 370,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-03 16:40:51',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-04 08:00:00',
                'id' => 50,
                'observaciones' => 'Pedido generado desde la planificacion: Bolivariana De Puertos Bolipuertos Sa',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-03 16:40:51',
                'vehiculo_id' => 45,
            ),
            41 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '30000.00',
                'chofer_id' => 11,
                'cliente_id' => 370,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-03 16:40:56',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-04 08:00:00',
                'id' => 51,
                'observaciones' => 'Pedido generado desde la planificacion: Bolivariana De Puertos Bolipuertos Sa',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-03 16:40:56',
                'vehiculo_id' => 45,
            ),
            42 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => 11,
                'cliente_id' => 336,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-05 15:14:57',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-05 14:00:00',
                'id' => 52,
                'observaciones' => 'Pedido generado desde la planificacion: SALVA FOODS 2015 C.A',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-05 15:14:57',
                'vehiculo_id' => 21,
            ),
            43 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => 10,
                'cliente_id' => 320,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-09 09:22:40',
                'deposito_id' => 6,
                'estado' => 'cancelado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-09 10:00:00',
                'id' => 53,
                'observaciones' => 'Pedido generado desde la planificacion: FORUM SUPER MAYORISTA SEDE CENTRO MATURIN',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-09 17:01:31',
                'vehiculo_id' => 21,
            ),
            44 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1500.00',
                'chofer_id' => 10,
                'cliente_id' => 298,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-09 16:02:12',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-10 09:00:00',
                'id' => 55,
                'observaciones' => 'Pedido generado desde la planificacion: Farmatodo Ca Tienda Autana',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-09 16:02:12',
                'vehiculo_id' => 13,
            ),
            45 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '5000.00',
                'chofer_id' => NULL,
                'cliente_id' => 2,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-09 16:04:16',
                'deposito_id' => NULL,
                'estado' => 'rechazado',
                'fecha_aprobacion' => '2025-12-09 16:23:09',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-09 16:04:16',
                'id' => 56,
                'observaciones' => 'para ya',
                'observaciones_admin' => 'no',
                'updated_at' => '2025-12-09 16:23:09',
                'vehiculo_id' => NULL,
            ),
            46 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '12000.00',
                'chofer_id' => NULL,
                'cliente_id' => 2,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-09 16:12:05',
                'deposito_id' => NULL,
                'estado' => 'rechazado',
                'fecha_aprobacion' => '2025-12-09 16:22:51',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-09 16:12:05',
                'id' => 57,
                'observaciones' => 'para mañana',
                'observaciones_admin' => 'no',
                'updated_at' => '2025-12-09 16:22:51',
                'vehiculo_id' => NULL,
            ),
            47 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '5000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '5000.00',
                'chofer_id' => NULL,
                'cliente_id' => 2,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-09 16:24:26',
                'deposito_id' => NULL,
                'estado' => 'cancelado',
                'fecha_aprobacion' => '2025-12-09 16:25:08',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-09 16:24:26',
                'id' => 58,
                'observaciones' => 'para mañana',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-09 16:36:19',
                'vehiculo_id' => NULL,
            ),
            48 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '2000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '2000.00',
                'chofer_id' => NULL,
                'cliente_id' => 2,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-09 16:42:14',
                'deposito_id' => NULL,
                'estado' => 'aprobado',
                'fecha_aprobacion' => '2025-12-09 16:43:11',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-09 16:42:14',
                'id' => 59,
                'observaciones' => 'para ya',
                'observaciones_admin' => 'En la tarde',
                'updated_at' => '2025-12-09 16:43:11',
                'vehiculo_id' => NULL,
            ),
            49 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '5000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '5000.00',
                'chofer_id' => 6,
                'cliente_id' => 374,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-09 16:52:06',
                'deposito_id' => NULL,
                'estado' => 'cancelado',
                'fecha_aprobacion' => '2025-12-09 16:53:22',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-09 16:52:06',
                'id' => 60,
                'observaciones' => 'por favor lo más rápido',
                'observaciones_admin' => 'Unidad N°15, Ayudante Alberto Piñero',
                'updated_at' => '2025-12-09 17:03:25',
                'vehiculo_id' => NULL,
            ),
            50 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => NULL,
                'cliente_id' => 2,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-09 16:55:51',
                'deposito_id' => NULL,
                'estado' => 'rechazado',
                'fecha_aprobacion' => '2025-12-09 16:56:16',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-09 16:55:51',
                'id' => 61,
                'observaciones' => 'xxx',
                'observaciones_admin' => 'no',
                'updated_at' => '2025-12-09 16:56:16',
                'vehiculo_id' => NULL,
            ),
            51 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '500.00',
                'chofer_id' => NULL,
                'cliente_id' => 2,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-09 16:56:54',
                'deposito_id' => NULL,
                'estado' => 'rechazado',
                'fecha_aprobacion' => '2025-12-09 16:58:35',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-09 16:56:54',
                'id' => 62,
                'observaciones' => 'perito',
                'observaciones_admin' => 'No seleccione otra fecha

Fechas disponibles 
34/12/2025',
                'updated_at' => '2025-12-09 16:58:35',
                'vehiculo_id' => NULL,
            ),
            52 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '10000.00',
                'chofer_id' => NULL,
                'cliente_id' => 2,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-09 17:00:08',
                'deposito_id' => NULL,
                'estado' => 'rechazado',
                'fecha_aprobacion' => '2025-12-09 17:00:55',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-09 17:00:08',
                'id' => 63,
                'observaciones' => 'para mañana 10 de diciembre',
                'observaciones_admin' => 'Disponible el combustible para el 26/12/25',
                'updated_at' => '2025-12-09 17:00:55',
                'vehiculo_id' => NULL,
            ),
            53 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '10000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '10000.00',
                'chofer_id' => NULL,
                'cliente_id' => 1,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-09 17:07:35',
                'deposito_id' => NULL,
                'estado' => 'en_proceso',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-10 01:00:00',
                'id' => 64,
                'observaciones' => 'gghh',
                'observaciones_admin' => 'gghhg | Fecha requerida: 2025-12-10 | Planificado para 2025-12-10 00:00:00',
                'updated_at' => '2025-12-09 17:07:38',
                'vehiculo_id' => NULL,
            ),
            54 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '20000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '20000.00',
                'chofer_id' => 6,
                'cliente_id' => 2,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-09 17:10:05',
                'deposito_id' => NULL,
                'estado' => 'cancelado',
                'fecha_aprobacion' => '2025-12-09 17:11:18',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-09 17:10:05',
                'id' => 65,
                'observaciones' => 'prueba bolipuertos',
                'observaciones_admin' => 'prueba app',
                'updated_at' => '2025-12-09 17:13:48',
                'vehiculo_id' => NULL,
            ),
            55 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '1000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => 6,
                'cliente_id' => 374,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-09 17:14:22',
                'deposito_id' => NULL,
                'estado' => 'aprobado',
                'fecha_aprobacion' => '2025-12-09 17:16:21',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-09 17:14:22',
                'id' => 66,
                'observaciones' => 'prueba',
                'observaciones_admin' => 'prueba',
                'updated_at' => '2025-12-09 17:16:21',
                'vehiculo_id' => NULL,
            ),
            56 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '10000.00',
                'chofer_id' => NULL,
                'cliente_id' => 2,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-09 17:17:32',
                'deposito_id' => NULL,
                'estado' => 'rechazado',
                'fecha_aprobacion' => '2025-12-09 17:18:24',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-09 17:17:32',
                'id' => 67,
                'observaciones' => 'prueba',
                'observaciones_admin' => 'para no hay diponible prueba para el 10/12/2025',
                'updated_at' => '2025-12-09 17:18:24',
                'vehiculo_id' => NULL,
            ),
            57 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '1000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => NULL,
                'cliente_id' => 2,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-09 17:22:04',
                'deposito_id' => NULL,
                'estado' => 'en_proceso',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-10 01:00:00',
                'id' => 68,
                'observaciones' => 'prueba',
                'observaciones_admin' => 'prueba | Fecha requerida: 2025-12-10 | Planificado para 2025-12-10 00:00:00',
                'updated_at' => '2025-12-09 17:22:08',
                'vehiculo_id' => NULL,
            ),
            58 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '12000.00',
                'chofer_id' => NULL,
                'cliente_id' => 379,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-09 17:36:27',
                'deposito_id' => NULL,
                'estado' => 'rechazado',
                'fecha_aprobacion' => '2025-12-09 17:50:14',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-09 17:36:27',
                'id' => 69,
                'observaciones' => 'Prueba',
                'observaciones_admin' => 'no',
                'updated_at' => '2025-12-09 17:50:14',
                'vehiculo_id' => NULL,
            ),
            59 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '12000.00',
                'chofer_id' => NULL,
                'cliente_id' => 379,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-09 17:48:30',
                'deposito_id' => NULL,
                'estado' => 'rechazado',
                'fecha_aprobacion' => '2025-12-09 17:49:44',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-09 17:48:30',
                'id' => 70,
                'observaciones' => 'para el día jueves',
                'observaciones_admin' => 'paracel 11 de dicienmbre',
                'updated_at' => '2025-12-09 17:49:44',
                'vehiculo_id' => NULL,
            ),
            60 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => '20000.00',
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '20000.00',
                'chofer_id' => 8,
                'cliente_id' => 379,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-09 17:50:47',
                'deposito_id' => NULL,
                'estado' => 'cancelado',
                'fecha_aprobacion' => '2025-12-09 17:51:31',
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-09 17:50:47',
                'id' => 71,
                'observaciones' => 'para puerto cabello',
                'observaciones_admin' => 'para el viernes',
                'updated_at' => '2025-12-09 17:59:03',
                'vehiculo_id' => NULL,
            ),
            61 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '12000.00',
                'chofer_id' => 11,
                'cliente_id' => 372,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-11 09:41:41',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-11 10:00:00',
                'id' => 72,
                'observaciones' => 'Pedido generado desde la planificacion: Bolivariana De Puertos Bolipuertos Sa',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-11 09:41:41',
                'vehiculo_id' => 16,
            ),
            62 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '30000.00',
                'chofer_id' => 11,
                'cliente_id' => 373,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-11 17:33:09',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-12 06:00:00',
                'id' => 73,
                'observaciones' => 'Pedido generado desde la planificacion: Bolivariana De Puertos Bolipuertos Sa',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-11 17:33:09',
                'vehiculo_id' => 45,
            ),
            63 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '900.00',
                'chofer_id' => 3,
                'cliente_id' => 304,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-11 18:18:51',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-12 07:00:00',
                'id' => 74,
                'observaciones' => 'Pedido generado desde la planificacion: Nestle De Venzuela Sa Sede Od Maracay',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-11 18:18:51',
                'vehiculo_id' => 18,
            ),
            64 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '7000.00',
                'chofer_id' => 3,
                'cliente_id' => 340,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-15 12:11:03',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-15 14:00:00',
                'id' => 75,
                'observaciones' => 'Pedido generado desde la planificacion: FARMASOLIDARIA 2021 C.A',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-15 12:11:03',
                'vehiculo_id' => 21,
            ),
            65 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '11000.00',
                'chofer_id' => 11,
                'cliente_id' => 369,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-15 12:13:14',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-15 14:00:00',
                'id' => 77,
                'observaciones' => 'Pedido generado desde la planificacion: Bolivariana De Puertos Bolipuertos Sa',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-15 12:13:14',
                'vehiculo_id' => 16,
            ),
            66 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '12000.00',
                'chofer_id' => 11,
                'cliente_id' => 340,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-15 12:21:23',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-15 14:00:00',
                'id' => 78,
                'observaciones' => 'Pedido generado desde la planificacion: FARMASOLIDARIA 2021 C.A',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-15 12:21:23',
                'vehiculo_id' => 16,
            ),
            67 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '12000.00',
                'chofer_id' => 11,
                'cliente_id' => 369,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-15 12:23:45',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-15 14:00:00',
                'id' => 79,
                'observaciones' => 'Pedido generado desde la planificacion: Bolivariana De Puertos Bolipuertos Sa',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-15 12:23:45',
                'vehiculo_id' => 16,
            ),
            68 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '3000.00',
                'chofer_id' => 10,
                'cliente_id' => 340,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-16 09:41:48',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-16 10:00:00',
                'id' => 80,
                'observaciones' => 'Pedido generado desde la planificacion: FARMASOLIDARIA 2021 C.A',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-16 09:41:48',
                'vehiculo_id' => 13,
            ),
            69 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1350.00',
                'chofer_id' => 3,
                'cliente_id' => 285,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-16 14:25:10',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-16 15:30:00',
                'id' => 82,
                'observaciones' => 'Pedido generado desde la planificacion: Forum Super Mayorista Ca Sede El Paraiso',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-16 14:25:10',
                'vehiculo_id' => 18,
            ),
            70 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '20000.00',
                'chofer_id' => 11,
                'cliente_id' => 372,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-26 10:27:08',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-26 11:00:00',
                'id' => 83,
                'observaciones' => 'Pedido generado desde la planificacion: Bolivariana De Puertos Bolipuertos Sa',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-26 10:27:08',
                'vehiculo_id' => 14,
            ),
            71 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '38000.00',
                'chofer_id' => 11,
                'cliente_id' => 373,
                'comentario_calificacion' => NULL,
                'created_at' => '2025-12-30 15:46:26',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2025-12-31 06:00:00',
                'id' => 84,
                'observaciones' => 'Pedido generado desde la planificacion: Bolivariana De Puertos Bolipuertos Sa',
                'observaciones_admin' => NULL,
                'updated_at' => '2025-12-30 15:46:26',
                'vehiculo_id' => 30,
            ),
            72 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '20000.00',
                'chofer_id' => 11,
                'cliente_id' => 370,
                'comentario_calificacion' => NULL,
                'created_at' => '2026-01-02 09:59:49',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2026-01-02 11:00:00',
                'id' => 85,
                'observaciones' => 'Pedido generado desde la planificacion: Bolivariana De Puertos Bolipuertos Sa',
                'observaciones_admin' => NULL,
                'updated_at' => '2026-01-02 09:59:49',
                'vehiculo_id' => 14,
            ),
            73 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1800.00',
                'chofer_id' => 11,
                'cliente_id' => 285,
                'comentario_calificacion' => NULL,
                'created_at' => '2026-01-05 10:05:36',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2026-01-05 10:00:00',
                'id' => 86,
                'observaciones' => 'Pedido generado desde la planificacion: Forum Super Mayorista Ca Sede El Paraiso',
                'observaciones_admin' => NULL,
                'updated_at' => '2026-01-05 10:05:36',
                'vehiculo_id' => 44,
            ),
            74 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '4500.00',
                'chofer_id' => 3,
                'cliente_id' => 366,
                'comentario_calificacion' => NULL,
                'created_at' => '2026-01-05 17:53:56',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2026-01-06 07:00:00',
                'id' => 87,
                'observaciones' => 'Pedido generado desde la planificacion: Bolivariana De Puertos Bolipuertos Sa',
                'observaciones_admin' => NULL,
                'updated_at' => '2026-01-05 17:53:56',
                'vehiculo_id' => 18,
            ),
            75 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '4000.00',
                'chofer_id' => 3,
                'cliente_id' => 340,
                'comentario_calificacion' => NULL,
                'created_at' => '2026-01-06 13:10:20',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2026-01-06 14:30:00',
                'id' => 88,
                'observaciones' => 'Pedido generado desde la planificacion: FARMASOLIDARIA 2021 C.A',
                'observaciones_admin' => NULL,
                'updated_at' => '2026-01-06 13:10:20',
                'vehiculo_id' => 13,
            ),
            76 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '10000.00',
                'chofer_id' => 10,
                'cliente_id' => 27,
                'comentario_calificacion' => NULL,
                'created_at' => '2026-01-06 16:05:16',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2026-01-07 08:30:00',
                'id' => 89,
                'observaciones' => 'Pedido generado desde la planificacion: INVERSIONES FONTANOL',
                'observaciones_admin' => NULL,
                'updated_at' => '2026-01-06 16:05:16',
                'vehiculo_id' => 16,
            ),
            77 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '20000.00',
                'chofer_id' => 6,
                'cliente_id' => 372,
                'comentario_calificacion' => NULL,
                'created_at' => '2026-01-07 17:04:13',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2026-01-08 09:00:00',
                'id' => 90,
                'observaciones' => 'Pedido generado desde la planificacion: Bolivariana De Puertos Bolipuertos Sa',
                'observaciones_admin' => NULL,
                'updated_at' => '2026-01-07 17:04:13',
                'vehiculo_id' => 14,
            ),
            78 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '2300.00',
                'chofer_id' => 3,
                'cliente_id' => 378,
                'comentario_calificacion' => NULL,
                'created_at' => '2026-01-07 17:22:31',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2026-01-08 07:00:00',
                'id' => 91,
                'observaciones' => 'Pedido generado desde la planificacion: SERVICOM C.A',
                'observaciones_admin' => NULL,
                'updated_at' => '2026-01-07 17:22:31',
                'vehiculo_id' => 21,
            ),
            79 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '400.00',
                'chofer_id' => 10,
                'cliente_id' => 286,
                'comentario_calificacion' => NULL,
                'created_at' => '2026-01-07 17:30:30',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2026-01-08 09:00:00',
                'id' => 92,
                'observaciones' => 'Pedido generado desde la planificacion: Forum Super Mayorista Ca Sede Los Molinos',
                'observaciones_admin' => NULL,
                'updated_at' => '2026-01-07 17:30:30',
                'vehiculo_id' => 13,
            ),
            80 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '36000.00',
                'chofer_id' => 11,
                'cliente_id' => 373,
                'comentario_calificacion' => NULL,
                'created_at' => '2026-01-13 14:47:58',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2026-01-14 06:00:00',
                'id' => 93,
                'observaciones' => 'Pedido generado desde la planificacion: Bolivariana De Puertos Bolipuertos Sa',
                'observaciones_admin' => NULL,
                'updated_at' => '2026-01-13 14:47:58',
                'vehiculo_id' => 17,
            ),
            81 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '2000.00',
                'chofer_id' => 10,
                'cliente_id' => 297,
                'comentario_calificacion' => NULL,
                'created_at' => '2026-01-16 09:30:37',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2026-01-16 10:00:00',
                'id' => 94,
                'observaciones' => 'Pedido generado desde la planificacion: Farmatodo Ca Tienda Tepuy',
                'observaciones_admin' => NULL,
                'updated_at' => '2026-01-16 09:30:37',
                'vehiculo_id' => 18,
            ),
            82 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '10000.00',
                'chofer_id' => 3,
                'cliente_id' => 27,
                'comentario_calificacion' => NULL,
                'created_at' => '2026-01-19 10:50:32',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2026-01-19 11:30:00',
                'id' => 95,
                'observaciones' => 'Pedido generado desde la planificacion: INVERSIONES FONTANOL',
                'observaciones_admin' => NULL,
                'updated_at' => '2026-01-19 10:50:32',
                'vehiculo_id' => 14,
            ),
            83 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '2000.00',
                'chofer_id' => 20,
                'cliente_id' => 378,
                'comentario_calificacion' => NULL,
                'created_at' => '2026-01-19 17:47:31',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2026-01-20 07:00:00',
                'id' => 97,
                'observaciones' => 'Pedido generado desde la planificacion: SERVICOM C.A',
                'observaciones_admin' => NULL,
                'updated_at' => '2026-01-19 17:47:31',
                'vehiculo_id' => 18,
            ),
            84 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '1000.00',
                'chofer_id' => 3,
                'cliente_id' => 281,
                'comentario_calificacion' => NULL,
                'created_at' => '2026-01-19 17:50:05',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2026-01-20 09:00:00',
                'id' => 98,
                'observaciones' => 'Pedido generado desde la planificacion: Forum Super Mayorista Ca Sede La Hoyada',
                'observaciones_admin' => NULL,
                'updated_at' => '2026-01-19 17:50:05',
                'vehiculo_id' => 13,
            ),
            85 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '12000.00',
                'chofer_id' => 11,
                'cliente_id' => 369,
                'comentario_calificacion' => NULL,
                'created_at' => '2026-01-20 12:36:27',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2026-01-20 14:00:00',
                'id' => 99,
                'observaciones' => 'Pedido generado desde la planificacion: Bolivariana De Puertos Bolipuertos Sa',
                'observaciones_admin' => NULL,
                'updated_at' => '2026-01-20 12:36:27',
                'vehiculo_id' => 16,
            ),
            86 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '5000.00',
                'chofer_id' => 11,
                'cliente_id' => 347,
                'comentario_calificacion' => NULL,
                'created_at' => '2026-01-20 16:52:51',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2026-01-21 09:00:00',
                'id' => 100,
                'observaciones' => 'Pedido generado desde la planificacion: NESTLE VENEZUELA S.A SEDE SANTA CRUZ',
                'observaciones_admin' => NULL,
                'updated_at' => '2026-01-20 16:52:51',
                'vehiculo_id' => 16,
            ),
            87 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '5000.00',
                'chofer_id' => 11,
                'cliente_id' => 305,
                'comentario_calificacion' => NULL,
                'created_at' => '2026-01-20 16:52:54',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2026-01-21 09:00:00',
                'id' => 101,
                'observaciones' => 'Pedido generado desde la planificacion: Nestle De Venezuela Sede La Encrucijada',
                'observaciones_admin' => NULL,
                'updated_at' => '2026-01-20 16:52:54',
                'vehiculo_id' => 16,
            ),
            88 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '5000.00',
                'chofer_id' => 11,
                'cliente_id' => 306,
                'comentario_calificacion' => NULL,
                'created_at' => '2026-01-20 16:55:58',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2026-01-21 08:00:00',
                'id' => 102,
                'observaciones' => 'Pedido generado desde la planificacion: Nestle De Venezuela Sa Sede  Santa Cruz',
                'observaciones_admin' => NULL,
                'updated_at' => '2026-01-20 16:55:58',
                'vehiculo_id' => 16,
            ),
            89 => 
            array (
                'calificacion' => NULL,
                'cantidad_aprobada' => NULL,
                'cantidad_recibida' => NULL,
                'cantidad_solicitada' => '5000.00',
                'chofer_id' => 11,
                'cliente_id' => 305,
                'comentario_calificacion' => NULL,
                'created_at' => '2026-01-20 16:56:01',
                'deposito_id' => 6,
                'estado' => 'aprobado',
                'fecha_aprobacion' => NULL,
                'fecha_completado' => NULL,
                'fecha_solicitud' => '2026-01-21 08:00:00',
                'id' => 103,
                'observaciones' => 'Pedido generado desde la planificacion: Nestle De Venezuela Sede La Encrucijada',
                'observaciones_admin' => NULL,
                'updated_at' => '2026-01-20 16:56:01',
                'vehiculo_id' => 16,
            ),
        ));
        
        
    }
}