<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PermisoPerfilTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('permiso_perfil')->delete();
        
        \DB::table('permiso_perfil')->insert(array (
            0 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 1,
                'id_modulo' => 1,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            1 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 2,
                'id_modulo' => 2,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            2 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 3,
                'id_modulo' => 3,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            3 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 4,
                'id_modulo' => 4,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            4 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 5,
                'id_modulo' => 5,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            5 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 6,
                'id_modulo' => 12,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            6 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 7,
                'id_modulo' => 13,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            7 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 8,
                'id_modulo' => 30,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            8 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 9,
                'id_modulo' => 31,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            9 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 10,
                'id_modulo' => 40,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            10 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 11,
                'id_modulo' => 42,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            11 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 12,
                'id_modulo' => 43,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            12 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 13,
                'id_modulo' => 44,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            13 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 14,
                'id_modulo' => 47,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            14 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 15,
                'id_modulo' => 51,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            15 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 16,
                'id_modulo' => 1,
                'id_perfil' => 2,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            16 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 17,
                'id_modulo' => 2,
                'id_perfil' => 2,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            17 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 18,
                'id_modulo' => 4,
                'id_perfil' => 2,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            18 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 19,
                'id_modulo' => 30,
                'id_perfil' => 2,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            19 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 20,
                'id_modulo' => 40,
                'id_perfil' => 2,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            20 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 21,
                'id_modulo' => 42,
                'id_perfil' => 2,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            21 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 22,
                'id_modulo' => 44,
                'id_perfil' => 2,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            22 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 23,
                'id_modulo' => 47,
                'id_perfil' => 2,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            23 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 1,
                'id' => 24,
                'id_modulo' => 51,
                'id_perfil' => 2,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            24 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 25,
                'id_modulo' => 3,
                'id_perfil' => 2,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            25 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 26,
                'id_modulo' => 5,
                'id_perfil' => 2,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            26 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 27,
                'id_modulo' => 12,
                'id_perfil' => 2,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            27 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 28,
                'id_modulo' => 13,
                'id_perfil' => 2,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            28 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 29,
                'id_modulo' => 31,
                'id_perfil' => 2,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            29 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 30,
                'id_modulo' => 43,
                'id_perfil' => 2,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            30 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 31,
                'id_modulo' => 1,
                'id_perfil' => 3,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            31 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 32,
                'id_modulo' => 2,
                'id_perfil' => 3,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            32 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 33,
                'id_modulo' => 42,
                'id_perfil' => 3,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            33 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 34,
                'id_modulo' => 1,
                'id_perfil' => 4,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            34 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 35,
                'id_modulo' => 44,
                'id_perfil' => 4,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            35 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 36,
                'id_modulo' => 42,
                'id_perfil' => 4,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            36 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 37,
                'id_modulo' => 47,
                'id_perfil' => 4,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            37 => 
            array (
                'create' => 1,
                'created_at' => NULL,
                'delete' => 1,
                'id' => 110,
                'id_modulo' => 6,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => NULL,
            ),
            38 => 
            array (
                'create' => 1,
                'created_at' => NULL,
                'delete' => 1,
                'id' => 109,
                'id_modulo' => 6,
                'id_perfil' => 6,
                'read' => 1,
                'update' => 1,
                'updated_at' => NULL,
            ),
            39 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-03 09:43:42',
                'delete' => 1,
                'id' => 108,
                'id_modulo' => 5,
                'id_perfil' => 12,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-03 09:43:42',
            ),
            40 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-03 09:43:42',
                'delete' => 0,
                'id' => 107,
                'id_modulo' => 4,
                'id_perfil' => 12,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-03 09:43:42',
            ),
            41 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 42,
                'id_modulo' => 1,
                'id_perfil' => 6,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            42 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 43,
                'id_modulo' => 2,
                'id_perfil' => 6,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            43 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 44,
                'id_modulo' => 30,
                'id_perfil' => 6,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            44 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 45,
                'id_modulo' => 40,
                'id_perfil' => 6,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            45 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 46,
                'id_modulo' => 42,
                'id_perfil' => 6,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            46 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 47,
                'id_modulo' => 1,
                'id_perfil' => 7,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            47 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 48,
                'id_modulo' => 2,
                'id_perfil' => 7,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            48 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 49,
                'id_modulo' => 4,
                'id_perfil' => 7,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            49 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 50,
                'id_modulo' => 42,
                'id_perfil' => 7,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            50 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 51,
                'id_modulo' => 47,
                'id_perfil' => 7,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            51 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 52,
                'id_modulo' => 3,
                'id_perfil' => 8,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            52 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 53,
                'id_modulo' => 30,
                'id_perfil' => 8,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            53 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 54,
                'id_modulo' => 31,
                'id_perfil' => 8,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            54 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 55,
                'id_modulo' => 40,
                'id_perfil' => 8,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            55 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 56,
                'id_modulo' => 42,
                'id_perfil' => 8,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            56 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 57,
                'id_modulo' => 12,
                'id_perfil' => 8,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            57 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 58,
                'id_modulo' => 13,
                'id_perfil' => 8,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            58 => 
            array (
                'create' => 1,
                'created_at' => NULL,
                'delete' => 1,
                'id' => 59,
                'id_modulo' => 52,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => NULL,
            ),
            59 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-03 09:43:42',
                'delete' => 0,
                'id' => 106,
                'id_modulo' => 30,
                'id_perfil' => 12,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-03 09:43:42',
            ),
            60 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-03 09:43:42',
                'delete' => 0,
                'id' => 105,
                'id_modulo' => 3,
                'id_perfil' => 12,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-03 09:43:42',
            ),
            61 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-03 09:43:42',
                'delete' => 0,
                'id' => 104,
                'id_modulo' => 2,
                'id_perfil' => 12,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-03 09:43:42',
            ),
            62 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-02 16:17:50',
                'delete' => 0,
                'id' => 86,
                'id_modulo' => 5,
                'id_perfil' => 5,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-02 16:17:50',
            ),
            63 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-02 16:17:50',
                'delete' => 0,
                'id' => 85,
                'id_modulo' => 45,
                'id_perfil' => 5,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-02 16:17:50',
            ),
            64 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-02 16:17:50',
                'delete' => 0,
                'id' => 84,
                'id_modulo' => 4,
                'id_perfil' => 5,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-02 16:17:50',
            ),
            65 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-02 16:17:50',
                'delete' => 0,
                'id' => 83,
                'id_modulo' => 3,
                'id_perfil' => 5,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-02 16:17:50',
            ),
            66 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-02 16:17:50',
                'delete' => 0,
                'id' => 82,
                'id_modulo' => 2,
                'id_perfil' => 5,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-02 16:17:50',
            ),
            67 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-02 16:17:50',
                'delete' => 0,
                'id' => 81,
                'id_modulo' => 13,
                'id_perfil' => 5,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-02 16:17:50',
            ),
            68 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-02 16:17:50',
                'delete' => 0,
                'id' => 80,
                'id_modulo' => 12,
                'id_perfil' => 5,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-02 16:17:50',
            ),
            69 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-02 16:17:50',
                'delete' => 0,
                'id' => 79,
                'id_modulo' => 11,
                'id_perfil' => 5,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-02 16:17:50',
            ),
            70 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-02 16:17:50',
                'delete' => 0,
                'id' => 78,
                'id_modulo' => 10,
                'id_perfil' => 5,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-02 16:17:50',
            ),
            71 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-02 16:17:50',
                'delete' => 0,
                'id' => 77,
                'id_modulo' => 1,
                'id_perfil' => 5,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-02 16:17:50',
            ),
            72 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-03 09:43:42',
                'delete' => 0,
                'id' => 103,
                'id_modulo' => 1,
                'id_perfil' => 12,
                'read' => 0,
                'update' => 1,
                'updated_at' => '2025-10-03 09:43:42',
            ),
            73 => 
            array (
                'create' => 1,
                'created_at' => NULL,
                'delete' => 1,
                'id' => 111,
                'id_modulo' => 6,
                'id_perfil' => 12,
                'read' => 1,
                'update' => 1,
                'updated_at' => NULL,
            ),
            74 => 
            array (
                'create' => 1,
                'created_at' => NULL,
                'delete' => 1,
                'id' => 112,
                'id_modulo' => 6,
                'id_perfil' => 12,
                'read' => 1,
                'update' => 1,
                'updated_at' => NULL,
            ),
            75 => 
            array (
                'create' => 1,
                'created_at' => NULL,
                'delete' => 1,
                'id' => 113,
                'id_modulo' => 7,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => NULL,
            ),
            76 => 
            array (
                'create' => 1,
                'created_at' => NULL,
                'delete' => 1,
                'id' => 114,
                'id_modulo' => 7,
                'id_perfil' => 6,
                'read' => 1,
                'update' => 1,
                'updated_at' => NULL,
            ),
            77 => 
            array (
                'create' => 1,
                'created_at' => NULL,
                'delete' => 1,
                'id' => 115,
                'id_modulo' => 7,
                'id_perfil' => 12,
                'read' => 1,
                'update' => 1,
                'updated_at' => NULL,
            ),
            78 => 
            array (
                'create' => 1,
                'created_at' => NULL,
                'delete' => 1,
                'id' => 116,
                'id_modulo' => 1,
                'id_perfil' => 12,
                'read' => 1,
                'update' => 1,
                'updated_at' => NULL,
            ),
            79 => 
            array (
                'create' => 1,
                'created_at' => NULL,
                'delete' => 1,
                'id' => 117,
                'id_modulo' => 8,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => NULL,
            ),
            80 => 
            array (
                'create' => 1,
                'created_at' => NULL,
                'delete' => 1,
                'id' => 118,
                'id_modulo' => 4,
                'id_perfil' => 18,
                'read' => 1,
                'update' => 1,
                'updated_at' => NULL,
            ),
            81 => 
            array (
                'create' => 1,
                'created_at' => NULL,
                'delete' => 1,
                'id' => 119,
                'id_modulo' => 8,
                'id_perfil' => 18,
                'read' => 1,
                'update' => 1,
                'updated_at' => NULL,
            ),
            82 => 
            array (
                'create' => 1,
                'created_at' => NULL,
                'delete' => 1,
                'id' => 120,
                'id_modulo' => 49,
                'id_perfil' => 18,
                'read' => 1,
                'update' => 1,
                'updated_at' => NULL,
            ),
            83 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 121,
                'id_modulo' => 51,
                'id_perfil' => 6,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            84 => 
            array (
                'create' => 0,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 122,
                'id_modulo' => 5,
                'id_perfil' => 6,
                'read' => 1,
                'update' => 0,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            85 => 
            array (
                'create' => 1,
                'created_at' => NULL,
                'delete' => 1,
                'id' => 123,
                'id_modulo' => 4,
                'id_perfil' => 6,
                'read' => 1,
                'update' => 1,
                'updated_at' => NULL,
            ),
            86 => 
            array (
                'create' => 1,
                'created_at' => NULL,
                'delete' => 1,
                'id' => 124,
                'id_modulo' => 52,
                'id_perfil' => 1,
                'read' => 1,
                'update' => 1,
                'updated_at' => NULL,
            ),
            87 => 
            array (
                'create' => 1,
                'created_at' => NULL,
                'delete' => 1,
                'id' => 125,
                'id_modulo' => 52,
                'id_perfil' => 18,
                'read' => 1,
                'update' => 1,
                'updated_at' => NULL,
            ),
            88 => 
            array (
                'create' => 1,
                'created_at' => NULL,
                'delete' => 1,
                'id' => 126,
                'id_modulo' => 52,
                'id_perfil' => 2,
                'read' => 1,
                'update' => 1,
                'updated_at' => NULL,
            ),
            89 => 
            array (
                'create' => 1,
                'created_at' => '2025-12-09 10:01:26',
                'delete' => 0,
                'id' => 127,
                'id_modulo' => 7,
                'id_perfil' => 19,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-12-09 10:01:26',
            ),
            90 => 
            array (
                'create' => 1,
                'created_at' => '2025-12-09 10:01:26',
                'delete' => 0,
                'id' => 128,
                'id_modulo' => 6,
                'id_perfil' => 19,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-12-09 10:01:26',
            ),
            91 => 
            array (
                'create' => 1,
                'created_at' => '2025-12-09 10:01:26',
                'delete' => 0,
                'id' => 129,
                'id_modulo' => 1,
                'id_perfil' => 19,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-12-09 10:01:26',
            ),
            92 => 
            array (
                'create' => 1,
                'created_at' => '2025-12-09 10:01:26',
                'delete' => 1,
                'id' => 130,
                'id_modulo' => 2,
                'id_perfil' => 19,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-12-09 10:01:26',
            ),
            93 => 
            array (
                'create' => 1,
                'created_at' => '2025-12-09 10:01:26',
                'delete' => 1,
                'id' => 131,
                'id_modulo' => 3,
                'id_perfil' => 19,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-12-09 10:01:26',
            ),
            94 => 
            array (
                'create' => 1,
                'created_at' => '2025-12-09 10:01:26',
                'delete' => 0,
                'id' => 132,
                'id_modulo' => 4,
                'id_perfil' => 19,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-12-09 10:01:26',
            ),
            95 => 
            array (
                'create' => 1,
                'created_at' => '2025-12-09 10:01:26',
                'delete' => 0,
                'id' => 133,
                'id_modulo' => 5,
                'id_perfil' => 19,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-12-09 10:01:26',
            ),
            96 => 
            array (
                'create' => 1,
                'created_at' => '2025-12-09 10:01:26',
                'delete' => 0,
                'id' => 134,
                'id_modulo' => 8,
                'id_perfil' => 19,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-12-09 10:01:26',
            ),
            97 => 
            array (
                'create' => 1,
                'created_at' => '2025-12-09 10:01:26',
                'delete' => 0,
                'id' => 135,
                'id_modulo' => 52,
                'id_perfil' => 19,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-12-09 10:01:26',
            ),
            98 => 
            array (
                'create' => 1,
                'created_at' => NULL,
                'delete' => 1,
                'id' => 136,
                'id_modulo' => 8,
                'id_perfil' => 2,
                'read' => 1,
                'update' => 1,
                'updated_at' => NULL,
            ),
            99 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 137,
                'id_modulo' => 49,
                'id_perfil' => 7,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            100 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 138,
                'id_modulo' => 52,
                'id_perfil' => 7,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
            101 => 
            array (
                'create' => 1,
                'created_at' => '2025-10-01 14:40:08',
                'delete' => 0,
                'id' => 139,
                'id_modulo' => 8,
                'id_perfil' => 7,
                'read' => 1,
                'update' => 1,
                'updated_at' => '2025-10-01 14:40:08',
            ),
        ));
        
        
    }
}