<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PersonasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('personas')->delete();
        
        \DB::table('personas')->insert(array (
            0 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2013-08-07 00:00:00',
                'date_of_birth' => NULL,
                'dni' => NULL,
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 1,
                'nombre' => 'LUIS LEUDO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => '0212-2615556',
                'updated_at' => '2025-11-19 18:16:45',
            ),
            1 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2014-03-24 00:00:00',
                'date_of_birth' => NULL,
                'dni' => NULL,
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 2,
                'nombre' => 'LEMIR MARTINEZ',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => '04241455523',
                'updated_at' => '2025-07-30 06:00:43',
            ),
            2 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2013-12-02 01:00:00',
                'date_of_birth' => NULL,
                'dni' => NULL,
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 3,
                'nombre' => 'INVERSIONES IMPORMOTOR LLS C.A.',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => '02129633570',
                'updated_at' => '2025-07-30 06:00:43',
            ),
            3 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2016-01-01 01:00:00',
                'date_of_birth' => NULL,
                'dni' => NULL,
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 4,
                'nombre' => 'FARMATODO - CENDIS',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => '0800 -327628636',
                'updated_at' => '2025-07-30 06:00:43',
            ),
            4 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2016-07-06 00:00:00',
                'date_of_birth' => NULL,
                'dni' => NULL,
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 5,
                'nombre' => 'INVERSIONES IMPORMOTOR LLS C.A. - MASTER',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => '0212-7633570',
                'updated_at' => '2025-07-30 06:00:43',
            ),
            5 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2017-07-06 00:00:00',
                'date_of_birth' => NULL,
                'dni' => '4075530',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 6,
                'nombre' => 'FRANZ DIAZ',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => '021294980016',
                'updated_at' => '2025-07-30 06:00:43',
            ),
            6 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2019-05-29 00:00:00',
                'date_of_birth' => NULL,
                'dni' => NULL,
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 7,
                'nombre' => 'EXCELSIOR GAMMA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => '0000',
                'updated_at' => '2025-07-30 06:00:43',
            ),
            7 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2020-01-04 01:00:00',
                'date_of_birth' => NULL,
                'dni' => NULL,
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 8,
                'nombre' => 'USER',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => '0000',
                'updated_at' => '2025-07-30 06:00:43',
            ),
            8 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2019-12-15 01:00:00',
                'date_of_birth' => NULL,
                'dni' => NULL,
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 9,
                'nombre' => 'COVENCAUCHO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-07-30 06:00:43',
            ),
            9 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-08-26 14:19:33',
                'date_of_birth' => NULL,
                'dni' => '3324455432',
                'dni_exp' => '2028-09-26',
                'gender' => NULL,
                'id' => 105,
                'nombre' => 'PUEBA TEST',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => '34435652435',
                'updated_at' => '2025-08-26 14:19:33',
            ),
            10 => 
            array (
                'address' => 'Av. Principal, Caracas',
                'city' => 'Caracas',
                'country' => 'Venezuela',
                'created_at' => '2025-08-27 12:58:01',
                'date_of_birth' => NULL,
                'dni' => 'V-87699321',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 123,
                'nombre' => 'ADMIN',
                'notes' => NULL,
                'state' => 'Distrito Capital',
                'telefono' => NULL,
                'updated_at' => '2025-08-27 12:58:01',
            ),
            11 => 
            array (
                'address' => 'Calle Principal 123',
                'city' => 'Madrid',
                'country' => 'España',
                'created_at' => '2025-08-27 13:13:30',
                'date_of_birth' => NULL,
                'dni' => '12345678A',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 124,
                'nombre' => 'NOMBRE COMPLETO',
                'notes' => NULL,
                'state' => 'Madrid',
                'telefono' => '+34 123 456 789',
                'updated_at' => '2025-08-27 13:13:30',
            ),
            12 => 
            array (
                'address' => 'Calle Principal 123',
                'city' => 'Madrid',
                'country' => 'España',
                'created_at' => '2025-08-27 14:26:26',
                'date_of_birth' => NULL,
                'dni' => '123456999',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 125,
                'nombre' => 'NOMBRE COMPLETO',
                'notes' => NULL,
                'state' => 'Madrid',
                'telefono' => '+34123456789',
                'updated_at' => '2025-08-27 14:26:26',
            ),
            13 => 
            array (
                'address' => 'Calle Principal 123',
                'city' => 'Madrid',
                'country' => 'España',
                'created_at' => '2025-08-27 15:54:59',
                'date_of_birth' => NULL,
                'dni' => '12386999',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 126,
                'nombre' => 'NOMBRE COMPLETO',
                'notes' => NULL,
                'state' => 'Madrid',
                'telefono' => '+34123456789',
                'updated_at' => '2025-08-27 15:54:59',
            ),
            14 => 
            array (
                'address' => 'Calle Principal 123',
                'city' => 'Madrid',
                'country' => 'España',
                'created_at' => '2025-08-27 17:28:32',
                'date_of_birth' => NULL,
                'dni' => '14912838',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 127,
                'nombre' => 'ANAIS QUINTERO',
                'notes' => NULL,
                'state' => 'Madrid',
                'telefono' => '+34123456789',
                'updated_at' => '2025-08-27 17:28:32',
            ),
            15 => 
            array (
                'address' => 'Calle Principal 123',
                'city' => 'Madrid',
                'country' => 'España',
                'created_at' => '2025-08-27 17:56:44',
                'date_of_birth' => NULL,
                'dni' => '9999343',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 128,
                'nombre' => 'NOMBRE COMPLETO',
                'notes' => NULL,
                'state' => 'Madrid',
                'telefono' => '+34123456789',
                'updated_at' => '2025-08-27 17:56:44',
            ),
            16 => 
            array (
                'address' => 'Calle Principal 123',
                'city' => 'Madrid',
                'country' => 'España',
                'created_at' => '2025-08-27 18:12:55',
                'date_of_birth' => NULL,
                'dni' => '2999343',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 129,
                'nombre' => 'NOMBRE COMPLETO',
                'notes' => NULL,
                'state' => 'Madrid',
                'telefono' => '+34123456789',
                'updated_at' => '2025-08-27 18:12:55',
            ),
            17 => 
            array (
                'address' => 'Calle Principal 123',
                'city' => 'Caracas',
                'country' => 'Venezuela',
                'created_at' => '2025-08-27 18:54:38',
                'date_of_birth' => NULL,
                'dni' => '123456789',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 130,
                'nombre' => 'TOMAS BELLO',
                'notes' => NULL,
                'state' => 'Dtto Capital',
                'telefono' => '',
                'updated_at' => '2025-08-27 18:54:38',
            ),
            18 => 
            array (
                'address' => 'Av. Principal, Caracas',
                'city' => 'Caracas',
                'country' => 'Venezuela',
                'created_at' => '2025-09-01 12:24:57',
                'date_of_birth' => NULL,
                'dni' => 'V-279932911',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 135,
                'nombre' => 'MECANICO1',
                'notes' => NULL,
                'state' => 'Distrito Capital',
                'telefono' => NULL,
                'updated_at' => '2025-09-01 12:24:57',
            ),
            19 => 
            array (
                'address' => 'Av. Principal, Caracas',
                'city' => 'Caracas',
                'country' => 'Venezuela',
                'created_at' => '2025-09-01 12:25:24',
                'date_of_birth' => NULL,
                'dni' => 'V-259932911',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 136,
                'nombre' => 'ADMIN',
                'notes' => NULL,
                'state' => 'Distrito Capital',
                'telefono' => NULL,
                'updated_at' => '2025-09-01 12:25:24',
            ),
            20 => 
            array (
                'address' => 'Av. Principal, Caracas',
                'city' => 'Caracas',
                'country' => 'Venezuela',
                'created_at' => '2025-09-01 13:03:40',
                'date_of_birth' => NULL,
                'dni' => 'V-119932911',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 137,
                'nombre' => 'CLIENTE',
                'notes' => NULL,
                'state' => 'Distrito Capital',
                'telefono' => NULL,
                'updated_at' => '2025-09-01 13:03:40',
            ),
            21 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:09',
                'date_of_birth' => NULL,
                'dni' => 'V6.561.557',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 142,
                'nombre' => 'D AMICO CARLESI MASSIMO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:09',
            ),
            22 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:09',
                'date_of_birth' => NULL,
                'dni' => 'V26.706.770',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 143,
                'nombre' => 'D AMICO MALDONADO MASSIMO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:09',
            ),
            23 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:09',
                'date_of_birth' => NULL,
                'dni' => 'V12.789.545',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 144,
                'nombre' => 'AULAR TROMPIZ NORKIS NOHEMI',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:09',
            ),
            24 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:09',
                'date_of_birth' => NULL,
                'dni' => 'V21.119.745',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 145,
                'nombre' => 'NEGRIN KARINA BETHELI',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:09',
            ),
            25 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:09',
                'date_of_birth' => NULL,
                'dni' => 'V24.787.838',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 146,
                'nombre' => 'GARCIA VARGAS JOSE RAFAEL',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:09',
            ),
            26 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:09',
                'date_of_birth' => NULL,
                'dni' => 'V16.669.525',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 147,
                'nombre' => 'PIÑATE OLIVEROS JULYMAR',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:09',
            ),
            27 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:09',
                'date_of_birth' => NULL,
                'dni' => 'V12.057.882',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 148,
                'nombre' => 'SIERVO SABASRKY MARCEL EDUARDO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:09',
            ),
            28 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:09',
                'date_of_birth' => NULL,
                'dni' => 'V13.437.400',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 149,
                'nombre' => 'ZURITA WILLIAMS ALEXANDER',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:09',
            ),
            29 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:09',
                'date_of_birth' => NULL,
                'dni' => 'V20.590.473',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 150,
                'nombre' => 'GUTIERREZ JAVIER',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:09',
            ),
            30 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:09',
                'date_of_birth' => NULL,
                'dni' => 'V10.276.273',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 151,
                'nombre' => 'LOPEZ JORGE',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:09',
            ),
            31 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:09',
                'date_of_birth' => NULL,
                'dni' => 'V25.234.868',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 152,
                'nombre' => 'HERGETA MENDOZA LUIS ENRIQUE',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:09',
            ),
            32 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:09',
                'date_of_birth' => NULL,
                'dni' => 'V25.990.382',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 153,
                'nombre' => 'HERNANDEZ CAMPOLI DANIELA ANDREYNA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:09',
            ),
            33 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:10',
                'date_of_birth' => NULL,
                'dni' => 'PDA0044181',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 154,
                'nombre' => 'CIONFOLI FRANCESCO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:10',
            ),
            34 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:10',
                'date_of_birth' => NULL,
                'dni' => 'PDA0050873',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 155,
                'nombre' => 'ODDONE GLORIA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:10',
            ),
            35 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:10',
                'date_of_birth' => NULL,
                'dni' => 'V15.708.713',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 156,
                'nombre' => 'TERAN VICTOR MANUEL',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:10',
            ),
            36 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:10',
                'date_of_birth' => NULL,
                'dni' => 'V14.121.217',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 157,
                'nombre' => 'CASTILLO SEQUERA KELLIS TROSKI',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:10',
            ),
            37 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:10',
                'date_of_birth' => NULL,
                'dni' => 'V24.636.714',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 158,
                'nombre' => 'YEPEZ LUQUE RONNIE VLADIMIR',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:10',
            ),
            38 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:10',
                'date_of_birth' => NULL,
                'dni' => 'V18.817.948',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 159,
                'nombre' => 'BRACHO ARDILA JOSE LEONARDO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:10',
            ),
            39 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:10',
                'date_of_birth' => NULL,
                'dni' => 'V4.278.790',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 160,
                'nombre' => 'GONZALEZ JUAN JESUS',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:10',
            ),
            40 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:10',
                'date_of_birth' => NULL,
                'dni' => 'V10.699.316',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 161,
                'nombre' => 'GALEA MORENO NEYDA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:10',
            ),
            41 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:10',
                'date_of_birth' => NULL,
                'dni' => 'V18.677.166',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 162,
                'nombre' => 'GONZALES DI MARINO RICARDO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:10',
            ),
            42 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:10',
                'date_of_birth' => NULL,
                'dni' => 'V23.613.888',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 163,
                'nombre' => 'MILANO MANUEL',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:10',
            ),
            43 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:10',
                'date_of_birth' => NULL,
                'dni' => 'V18.915.539',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 164,
                'nombre' => 'MONTENEGRO KARLA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:10',
            ),
            44 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:10',
                'date_of_birth' => NULL,
                'dni' => 'V21.240.600',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 165,
                'nombre' => 'PEINADO NITXON',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:10',
            ),
            45 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:11',
                'date_of_birth' => NULL,
                'dni' => 'V18.271.935',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 166,
                'nombre' => 'OROPEZA KELVIS',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:11',
            ),
            46 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:11',
                'date_of_birth' => NULL,
                'dni' => 'V15.837.855',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 167,
                'nombre' => 'GARCIA JULIO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:11',
            ),
            47 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:11',
                'date_of_birth' => NULL,
                'dni' => 'V17.687.588',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 168,
                'nombre' => 'PEÑA GREIBYS',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:11',
            ),
            48 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:11',
                'date_of_birth' => NULL,
                'dni' => 'V8.253.175',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 169,
                'nombre' => 'BOUSQUET FLORES CARLOS RAFAEL',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:11',
            ),
            49 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:11',
                'date_of_birth' => NULL,
                'dni' => 'V17.168.271',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 170,
                'nombre' => 'GONZALEZ LEOREMYS',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:11',
            ),
            50 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:11',
                'date_of_birth' => NULL,
                'dni' => 'V10.814.052',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 171,
                'nombre' => 'RIVAS YOHANA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:11',
            ),
            51 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:11',
                'date_of_birth' => NULL,
                'dni' => 'V24.796.723',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 172,
                'nombre' => 'BRAZON MARTINEZ ALEXANDER RAMON',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:11',
            ),
            52 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:11',
                'date_of_birth' => NULL,
                'dni' => 'V16.082.919',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 173,
                'nombre' => 'MENCIAS YOLEIZA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:11',
            ),
            53 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:11',
                'date_of_birth' => NULL,
                'dni' => 'V23.618.312',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 174,
                'nombre' => 'AROCHA LUIS',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:11',
            ),
            54 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:11',
                'date_of_birth' => NULL,
                'dni' => 'V20.871.247',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 175,
                'nombre' => 'MARTINEZ NELSON',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:11',
            ),
            55 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:11',
                'date_of_birth' => NULL,
                'dni' => 'V24.636.524',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 176,
                'nombre' => 'HERNANDEZ RICARDO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:11',
            ),
            56 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:12',
                'date_of_birth' => NULL,
                'dni' => 'V21.130.831',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 177,
                'nombre' => 'CORES MARIA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:12',
            ),
            57 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:12',
                'date_of_birth' => NULL,
                'dni' => 'V15.470.902',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 178,
                'nombre' => 'PIÑERO MARVIN',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:12',
            ),
            58 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:12',
                'date_of_birth' => NULL,
                'dni' => 'V17.309.325',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 179,
                'nombre' => 'NAVEDA JULIO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:12',
            ),
            59 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:12',
                'date_of_birth' => NULL,
                'dni' => 'V14.261.713',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 180,
                'nombre' => 'URBINA JAVIER',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:12',
            ),
            60 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:12',
                'date_of_birth' => NULL,
                'dni' => 'V22.904.530',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 181,
                'nombre' => 'GOMEZ DIONALDO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:12',
            ),
            61 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:12',
                'date_of_birth' => NULL,
                'dni' => 'V12.829.895',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 182,
                'nombre' => 'SANCHEZ CARLOS',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:12',
            ),
            62 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:12',
                'date_of_birth' => NULL,
                'dni' => 'V15.823.750',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 183,
                'nombre' => 'LAZZAROTTO GIUSEPPE',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:12',
            ),
            63 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:12',
                'date_of_birth' => NULL,
                'dni' => 'V12.997.235',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 184,
                'nombre' => 'BLANCO ORLANDO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:12',
            ),
            64 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:12',
                'date_of_birth' => NULL,
                'dni' => 'V16.495.718',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 185,
                'nombre' => 'TORO ALI',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:12',
            ),
            65 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:12',
                'date_of_birth' => NULL,
                'dni' => 'V20.017.081',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 186,
                'nombre' => 'MELENDEZ AIRAM',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:12',
            ),
            66 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:13',
                'date_of_birth' => NULL,
                'dni' => 'V17.512.399',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 187,
                'nombre' => 'ARIAS JOSE',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:13',
            ),
            67 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:13',
                'date_of_birth' => NULL,
                'dni' => 'V14.482.271',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 188,
                'nombre' => 'REVILLA MARIA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:13',
            ),
            68 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:13',
                'date_of_birth' => NULL,
                'dni' => 'V17.017.237',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 189,
                'nombre' => 'SALAZAR CARLOS',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:13',
            ),
            69 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:13',
                'date_of_birth' => NULL,
                'dni' => 'V19.061.803',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 190,
                'nombre' => 'LEON SERGIO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:13',
            ),
            70 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:13',
                'date_of_birth' => NULL,
                'dni' => 'V25.467.766',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 191,
                'nombre' => 'SANCHEZ ZORENA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:13',
            ),
            71 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:13',
                'date_of_birth' => NULL,
                'dni' => 'V20.308.902',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 192,
                'nombre' => 'LOPEZ AXEL',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:13',
            ),
            72 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:13',
                'date_of_birth' => NULL,
                'dni' => 'V19.228.101',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 193,
                'nombre' => 'AGELVIS CARLOS ',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:13',
            ),
            73 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:13',
                'date_of_birth' => NULL,
                'dni' => 'V22.354.932',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 194,
                'nombre' => 'NARANJO LICEIDI',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:13',
            ),
            74 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:13',
                'date_of_birth' => NULL,
                'dni' => 'V16.461.581',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 195,
                'nombre' => 'JEAN BRITO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:13',
            ),
            75 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:13',
                'date_of_birth' => NULL,
                'dni' => 'V20.653.282',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 196,
                'nombre' => 'PACACIOS ZULENNY',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:13',
            ),
            76 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:13',
                'date_of_birth' => NULL,
                'dni' => 'V15.710.445',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 197,
                'nombre' => 'PEREZ ELLUZ',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:13',
            ),
            77 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:13',
                'date_of_birth' => NULL,
                'dni' => 'V17.856.198',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 198,
                'nombre' => 'TOVAR JHONNY',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:13',
            ),
            78 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:14',
                'date_of_birth' => NULL,
                'dni' => 'V26.443.818',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 199,
                'nombre' => 'CORONEL YSYANIREL ',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:14',
            ),
            79 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:14',
                'date_of_birth' => NULL,
                'dni' => 'V27.387.042',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 200,
                'nombre' => 'LAGUNA OSCAR',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:14',
            ),
            80 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:14',
                'date_of_birth' => NULL,
                'dni' => 'V19.465.952',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 201,
                'nombre' => 'HERRERA DANNY',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:14',
            ),
            81 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:14',
                'date_of_birth' => NULL,
                'dni' => 'V23.596.890',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 202,
                'nombre' => 'PEÑA YOLIBET',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:14',
            ),
            82 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:14',
                'date_of_birth' => NULL,
                'dni' => 'V16.005.125',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 203,
                'nombre' => 'ATENCIO DELIA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:14',
            ),
            83 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:14',
                'date_of_birth' => NULL,
                'dni' => 'V20.723.169',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 204,
                'nombre' => 'ACOSTA MARIA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:14',
            ),
            84 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:14',
                'date_of_birth' => NULL,
                'dni' => 'V21.516.011',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 205,
                'nombre' => 'GUEVARA ERICK',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:14',
            ),
            85 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:14',
                'date_of_birth' => NULL,
                'dni' => 'V17.718.483',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 206,
                'nombre' => 'PRIMERA RONY',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:14',
            ),
            86 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:14',
                'date_of_birth' => NULL,
                'dni' => 'V27.569.275',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 207,
                'nombre' => 'FLORES MARY',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:14',
            ),
            87 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:14',
                'date_of_birth' => NULL,
                'dni' => 'V24.125.952',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 208,
                'nombre' => 'MORENO YURITZA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:14',
            ),
            88 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:14',
                'date_of_birth' => NULL,
                'dni' => 'V19.015.984',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 209,
                'nombre' => 'JIMENEZ LILIBETH',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:14',
            ),
            89 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:14',
                'date_of_birth' => NULL,
                'dni' => 'V19.195.816',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 210,
                'nombre' => 'MUJICA DIANNY',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:14',
            ),
            90 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:15',
                'date_of_birth' => NULL,
                'dni' => 'V19.817.829',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 211,
                'nombre' => 'ANZOLA GERALDINE',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:15',
            ),
            91 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:15',
                'date_of_birth' => NULL,
                'dni' => 'V17.034.446',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 212,
                'nombre' => 'VALERA LEIDY',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:15',
            ),
            92 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:15',
                'date_of_birth' => NULL,
                'dni' => 'V20.022.990',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 213,
                'nombre' => 'CORDOVA DAVID ',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:15',
            ),
            93 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:15',
                'date_of_birth' => NULL,
                'dni' => 'V13.846.510',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 214,
                'nombre' => 'ROSALES XIOMARA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:15',
            ),
            94 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:15',
                'date_of_birth' => NULL,
                'dni' => 'V23.690.488',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 215,
                'nombre' => 'RAMIREZ YUSNERY',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:15',
            ),
            95 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:15',
                'date_of_birth' => NULL,
                'dni' => 'V19.016.835',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 216,
                'nombre' => 'SANABRIA  NESTY',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:15',
            ),
            96 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:15',
                'date_of_birth' => NULL,
                'dni' => 'V15.783.807',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 217,
                'nombre' => 'GUERRERO JUAN',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:15',
            ),
            97 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:15',
                'date_of_birth' => NULL,
                'dni' => 'V20.808.744',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 218,
                'nombre' => 'JIMENEZ MARIA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:15',
            ),
            98 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:15',
                'date_of_birth' => NULL,
                'dni' => 'V15.357.200',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 219,
                'nombre' => 'COMTRERAS ERIKA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:15',
            ),
            99 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:15',
                'date_of_birth' => NULL,
                'dni' => 'V20.292.604',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 220,
                'nombre' => 'CARREÑO DIVEANA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:15',
            ),
            100 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:15',
                'date_of_birth' => NULL,
                'dni' => 'V25.357.489',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 221,
                'nombre' => 'MOGOLLON ROXANA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:15',
            ),
            101 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:16',
                'date_of_birth' => NULL,
                'dni' => 'V15.218.542',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 222,
                'nombre' => 'MOGOLLON  CARLOS',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:16',
            ),
            102 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:16',
                'date_of_birth' => NULL,
                'dni' => 'V22.423.278',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 223,
                'nombre' => 'BROCHERO FRANGELYS',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:16',
            ),
            103 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:16',
                'date_of_birth' => NULL,
                'dni' => 'V23.436.432',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 224,
                'nombre' => 'OLLARVEZ MARIANGELICA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:16',
            ),
            104 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:16',
                'date_of_birth' => NULL,
                'dni' => 'V12.726.263',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 225,
                'nombre' => 'HERRERA GIOREMI',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:16',
            ),
            105 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:16',
                'date_of_birth' => NULL,
                'dni' => 'V12.937.904',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 226,
                'nombre' => 'DURAN ESPERANZA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:16',
            ),
            106 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:16',
                'date_of_birth' => NULL,
                'dni' => 'V16.205.171',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 227,
                'nombre' => 'DUQUE HUBEISY',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:16',
            ),
            107 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:16',
                'date_of_birth' => NULL,
                'dni' => 'V18.039.223',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 228,
                'nombre' => 'RIVERA MIGUEL',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:16',
            ),
            108 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:16',
                'date_of_birth' => NULL,
                'dni' => 'V10.273.619',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 229,
                'nombre' => 'DURAN JOSE',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:16',
            ),
            109 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:16',
                'date_of_birth' => NULL,
                'dni' => 'V15.301.820',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 230,
                'nombre' => 'SOSA EDGAR',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:16',
            ),
            110 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:16',
                'date_of_birth' => NULL,
                'dni' => 'V16.130.075',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 231,
                'nombre' => 'RANGEL JANATHAN',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:16',
            ),
            111 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:16',
                'date_of_birth' => NULL,
                'dni' => 'V17.365.373',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 232,
                'nombre' => 'HERNANDEZ CARLOS',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:16',
            ),
            112 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:16',
                'date_of_birth' => NULL,
                'dni' => 'V7.127.992',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 233,
                'nombre' => 'HERNANDEZ AKIDA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:16',
            ),
            113 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:17',
                'date_of_birth' => NULL,
                'dni' => 'V9.661.782',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 234,
                'nombre' => 'RODRIGUEZ JOE',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-09-03 20:33:17',
            ),
            114 => 
            array (
                'address' => 'tester',
                'city' => 'caracas',
                'country' => 'velezuela',
                'created_at' => '2025-10-07 15:59:05',
                'date_of_birth' => NULL,
                'dni' => '6427038',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 241,
                'nombre' => 'IVAN CASTRO',
                'notes' => NULL,
                'state' => 'distrito capitdl',
                'telefono' => '+584143149719',
                'updated_at' => '2025-10-07 15:59:05',
            ),
            115 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '11.942.634',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 242,
                'nombre' => 'JOSE MONTILLA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            116 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '11.931.125',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 243,
                'nombre' => 'PEDRO MATA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            117 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '13.114.214',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 244,
                'nombre' => 'RODOLFO PADRON',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            118 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '15.168.440',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 245,
                'nombre' => 'FREDIS MARRIAGA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            119 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '15.870.536',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 247,
                'nombre' => 'BRENITTE SILVA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => '04241357846',
                'updated_at' => '2025-11-06 17:06:22',
            ),
            120 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '14.839.101',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 248,
                'nombre' => 'RAFAEL MONTANEZ',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            121 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '22.500.458',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 249,
                'nombre' => 'JAVIER TORRES',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            122 => 
            array (
                'address' => 'petare',
                'city' => 'caracas',
                'country' => 'Venezuela',
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '31.185.386',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 250,
                'nombre' => 'LUIS ROCHA',
                'notes' => NULL,
                'state' => 'miranda',
                'telefono' => '04120250705',
                'updated_at' => '2025-11-04 16:39:47',
            ),
            123 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => 'V 24.058.155',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 251,
                'nombre' => 'YHENDER BOSTANIO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            124 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => 'V10.690.824',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 252,
                'nombre' => 'MARIANO HERNANDEZ',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            125 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '11111111111122',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 253,
                'nombre' => 'JULIMAR CASTELLANO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            126 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '222222222',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 254,
                'nombre' => 'OSCAR OSORIO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            127 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '1232413',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 255,
                'nombre' => 'GUILLERMO JARAMILLO
',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            128 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '33333442',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 256,
                'nombre' => 'EVELYN ARTAGA
',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            129 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '6657545445',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 257,
                'nombre' => 'LOURDES',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            130 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '2225445',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 258,
                'nombre' => 'YELITZA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            131 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '77676213',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 259,
                'nombre' => 'GUILBERT',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            132 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2014-03-24 00:00:00',
                'date_of_birth' => NULL,
                'dni' => NULL,
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 260,
                'nombre' => 'CRNE ROJAS PEREZ',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => '04242035692',
                'updated_at' => '2025-07-30 06:00:43',
            ),
            133 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '16857181',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 261,
                'nombre' => 'RICARDO CONTRERAS',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            134 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => 'J-075770366',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 262,
                'nombre' => 'HÉCTOR REYES ',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            135 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => 'J- 411046396',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 263,
                'nombre' => 'JOSÉ LORES LYA SERVICE',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            136 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => 'J-503609348',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 264,
                'nombre' => 'ENGELBERTH ROJAS',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            137 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => 'J-075140427',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 265,
                'nombre' => 'JORGE',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            138 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-12-08 11:15:37',
                'date_of_birth' => NULL,
                'dni' => '30.821.362',
                'dni_exp' => '2025-06-30',
                'gender' => NULL,
                'id' => 266,
                'nombre' => 'GABRIEL HERNANDEZ',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-12-08 11:15:37',
            ),
            139 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-12-08 11:21:48',
                'date_of_birth' => NULL,
                'dni' => '30821362',
                'dni_exp' => '2015-06-26',
                'gender' => NULL,
                'id' => 267,
                'nombre' => 'JOSÉ GABRIEL HERNÁNDEZ GRANADILLO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => '2025-12-08 11:21:48',
            ),
            140 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:09',
                'date_of_birth' => NULL,
                'dni' => '14.789.421',
                'dni_exp' => '2035-08-01',
                'gender' => NULL,
                'id' => 268,
                'nombre' => 'DENNYS CARRANZA',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => '04123632079',
                'updated_at' => '2025-09-03 20:33:09',
            ),
            141 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '31.957.506',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 269,
                'nombre' => 'YESENIA VALERO',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => '04143907011',
                'updated_at' => NULL,
            ),
            142 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => '2025-09-03 20:33:09',
                'date_of_birth' => NULL,
                'dni' => '27.007.500',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 272,
                'nombre' => 'MADINSON ANTOLINEZ',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => '',
                'updated_at' => '2025-09-03 20:33:09',
            ),
            143 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '9414102',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 274,
                'nombre' => 'Hugo Hernandez',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            144 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '30614626
',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 275,
                'nombre' => 'Jean Carlos Correia',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
            145 => 
            array (
                'address' => NULL,
                'city' => NULL,
                'country' => NULL,
                'created_at' => NULL,
                'date_of_birth' => NULL,
                'dni' => '12.375.764',
                'dni_exp' => NULL,
                'gender' => NULL,
                'id' => 276,
                'nombre' => 'INFANTE, DANIEL',
                'notes' => NULL,
                'state' => NULL,
                'telefono' => NULL,
                'updated_at' => NULL,
            ),
        ));
        
        
    }
}