<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PersonalTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('personal')->delete();
        
        \DB::table('personal')->insert(array (
            0 => 
            array (
                'apellido' => 'ARCIA',
                'cargo' => 'TECNICO AUTOMOTRIZ',
                'ci' => '15894773',
                'dependencia' => 0,
                'direccion' => 'CIUDAD CARIBIA',
                'email' => 'ARCIAIVAN@HOTMAIL.COM',
                'estatus' => 1,
                'fecha_in' => '21-02-2014',
                'id_taller' => 1,
                'id_taller_personal' => 8,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'IVAN',
                'observaciones' => '',
                'telefono' => '04141955209',
            ),
            1 => 
            array (
                'apellido' => 'PEREZ',
                'cargo' => 'Mecánico',
                'ci' => '123456789',
                'dependencia' => 0,
                'direccion' => '',
                'email' => 'jose@hotmail.com',
                'estatus' => 1,
                'fecha_in' => '10-04-2014',
                'id_taller' => 1,
                'id_taller_personal' => 11,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'JOSE ',
                'observaciones' => '',
                'telefono' => '3456789',
            ),
            2 => 
            array (
                'apellido' => 'UBAN',
                'cargo' => 'jefe de taller',
                'ci' => '22037091',
                'dependencia' => 0,
                'direccion' => 'ALTO PRADO',
                'email' => 'CHINOUBAN@GMAIL.COM',
                'estatus' => 1,
                'fecha_in' => '30-10-2014',
                'id_taller' => 1,
                'id_taller_personal' => 20,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'ALVARO',
                'observaciones' => '',
                'telefono' => '04123200223',
            ),
            3 => 
            array (
                'apellido' => 'CASTELLANO',
                'cargo' => 'ASESORA DE SERVICIO Y REPUESTOS',
                'ci' => '17302116',
                'dependencia' => 0,
                'direccion' => 'BARUTA',
                'email' => 'IMPORMOTOR.REP@GMAIL.COM',
                'estatus' => 1,
                'fecha_in' => '03-11-2014',
                'id_taller' => 1,
                'id_taller_personal' => 21,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'JULYMAR ',
                'observaciones' => '',
                'telefono' => '04241310740',
            ),
            4 => 
            array (
                'apellido' => 'guia goyo',
                'cargo' => 'ayudante mecanico',
                'ci' => '18911622',
                'dependencia' => 0,
                'direccion' => 'parroquia macarao las adjuntas',
                'email' => 'alejandroguia7@gmail.com',
                'estatus' => 1,
                'fecha_in' => '05-11-2014',
                'id_taller' => 1,
                'id_taller_personal' => 22,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'luis alejandro',
                'observaciones' => '',
                'telefono' => '04141260975',
            ),
            5 => 
            array (
                'apellido' => 'SALAS',
                'cargo' => 'TECNICO AUTOMOTRIZ',
                'ci' => '24088644',
                'dependencia' => 0,
                'direccion' => 'bello campo',
                'email' => 'juanalas@hotmail.com',
                'estatus' => 1,
                'fecha_in' => '05-01-2015',
                'id_taller' => 1,
                'id_taller_personal' => 23,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'JUAN',
                'observaciones' => '',
                'telefono' => '04241516260',
            ),
            6 => 
            array (
                'apellido' => 'WALY',
                'cargo' => 'GERENTE GENERAL',
                'ci' => '12345678',
                'dependencia' => 0,
                'direccion' => 'CALLE EL COLEGIO',
                'email' => 'WALY@GMAIL.COM',
                'estatus' => 1,
                'fecha_in' => '09-04-2015',
                'id_taller' => 1,
                'id_taller_personal' => 26,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'WALY',
                'observaciones' => '',
                'telefono' => '04248056997',
            ),
            7 => 
            array (
                'apellido' => 'ORTIZ',
                'cargo' => 'Jefe de Taller',
                'ci' => '22352659',
                'dependencia' => 217,
                'direccion' => 'CHARALLAVE',
                'email' => 'MAYKERWYN@FARMATODO.COM',
                'estatus' => 1,
                'fecha_in' => '2020-08-12',
                'id_taller' => 1,
                'id_taller_personal' => 27,
                'id_usuario' => 1,
                'jefe_taller' => 1,
                'nombre' => 'JULIAN',
                'observaciones' => '',
                'telefono' => '04141742341',
            ),
            8 => 
            array (
                'apellido' => 'AZOCAR',
                'cargo' => 'Mecánico Tecnico',
                'ci' => '21.258.068',
                'dependencia' => 0,
                'direccion' => 'san casimiro aragua',
                'email' => 'tallermecanico@farmatodo.com',
                'estatus' => 1,
                'fecha_in' => '2020-08-12',
                'id_taller' => 1,
                'id_taller_personal' => 28,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'GERMAN',
                'observaciones' => '',
            'telefono' => '(0424)2494311',
            ),
            9 => 
            array (
                'apellido' => 'BERRIOS',
                'cargo' => 'Ayudante Mecánico',
                'ci' => '26.150.685',
                'dependencia' => 217,
                'direccion' => 'santa teresa del tuy',
                'email' => 'tallermecanico@farmatodo.com',
                'estatus' => 1,
                'fecha_in' => '15-06-2016',
                'id_taller' => 1,
                'id_taller_personal' => 29,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'MIGUEL',
                'observaciones' => '',
            'telefono' => '(0412)9918114',
            ),
            10 => 
            array (
                'apellido' => 'GONZALEZ',
                'cargo' => 'Mecánico 1',
                'ci' => '14.014.275',
                'dependencia' => 0,
                'direccion' => '',
                'email' => 'tallermecanico@farmatodo.com',
                'estatus' => 1,
                'fecha_in' => '15-06-2016',
                'id_taller' => 1,
                'id_taller_personal' => 32,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'GILBERTO',
                'observaciones' => '',
            'telefono' => '(0414)3990416',
            ),
            11 => 
            array (
                'apellido' => 'FERMIN',
                'cargo' => 'Mecánico 1',
                'ci' => '6.229.384',
                'dependencia' => 217,
                'direccion' => '',
                'email' => 'tallermecanico@farmatodo.com',
                'estatus' => 1,
                'fecha_in' => '15-06-2016',
                'id_taller' => 1,
                'id_taller_personal' => 33,
                'id_usuario' => 1,
                'jefe_taller' => 1,
                'nombre' => 'JORGE',
                'observaciones' => '',
            'telefono' => '(0424)1037303/(0416)9162618',
            ),
            12 => 
            array (
                'apellido' => 'LANDAETA',
                'cargo' => 'Mecánico 1',
                'ci' => '10.889.194',
                'dependencia' => 0,
                'direccion' => '',
                'email' => 'tallermecanico@farmatodo.com',
                'estatus' => 1,
                'fecha_in' => '15-06-2016',
                'id_taller' => 1,
                'id_taller_personal' => 34,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'ANTONIO ',
                'observaciones' => '',
            'telefono' => '(0424)1374020',
            ),
            13 => 
            array (
                'apellido' => 'RIVAS',
                'cargo' => 'Mecánico 1',
                'ci' => '14.154.756',
                'dependencia' => 0,
                'direccion' => '',
                'email' => 'tallermecanico@farmatodo.com',
                'estatus' => 1,
                'fecha_in' => '15-06-2016',
                'id_taller' => 1,
                'id_taller_personal' => 35,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'WASCAR',
                'observaciones' => '',
            'telefono' => '(0424)1844756',
            ),
            14 => 
            array (
                'apellido' => 'SOLORZANO',
                'cargo' => 'Ayudante Mecánico',
                'ci' => '14.642.250',
                'dependencia' => 0,
                'direccion' => '',
                'email' => 'tallermecanico@farmatodo.com',
                'estatus' => 1,
                'fecha_in' => '15-06-2016',
                'id_taller' => 1,
                'id_taller_personal' => 37,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'LUIS',
                'observaciones' => '',
            'telefono' => '(0426)7440377',
            ),
            15 => 
            array (
                'apellido' => 'SANCHEZ',
                'cargo' => 'Ayudante Mecánico',
                'ci' => '19.335.229',
                'dependencia' => 0,
                'direccion' => '',
                'email' => 'tallermecanico@farmatodo.com',
                'estatus' => 1,
                'fecha_in' => '15-06-2016',
                'id_taller' => 1,
                'id_taller_personal' => 38,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'YORDANI',
                'observaciones' => '',
            'telefono' => '(0426)4110790',
            ),
            16 => 
            array (
                'apellido' => 'BARRERA',
                'cargo' => 'Ayudante Mecánico',
                'ci' => '22.694.224',
                'dependencia' => 217,
                'direccion' => '',
                'email' => 'tallermecanico@farmatodo.com',
                'estatus' => 1,
                'fecha_in' => '15-06-2016',
                'id_taller' => 1,
                'id_taller_personal' => 39,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'JOSE',
                'observaciones' => '',
            'telefono' => '(0424)2130739',
            ),
            17 => 
            array (
                'apellido' => 'ROMERO',
                'cargo' => 'Ayudante Mecánico',
                'ci' => '14.966.732',
                'dependencia' => 0,
                'direccion' => '',
                'email' => 'tallermecanico@farmatodo.com',
                'estatus' => 1,
                'fecha_in' => '15-06-2016',
                'id_taller' => 1,
                'id_taller_personal' => 40,
                'id_usuario' => 1,
                'jefe_taller' => 1,
                'nombre' => 'MIGUEL',
                'observaciones' => '',
            'telefono' => '(0414)3029640',
            ),
            18 => 
            array (
                'apellido' => 'MEDINA',
                'cargo' => 'Ayudante Mecánico',
                'ci' => '20.490.540',
                'dependencia' => 217,
                'direccion' => ' ',
                'email' => 'tallermecanico@farmatodo.com',
                'estatus' => 1,
                'fecha_in' => '15-06-2016',
                'id_taller' => 1,
                'id_taller_personal' => 42,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'ODALIS',
                'observaciones' => '',
            'telefono' => '(0414)7862615',
            ),
            19 => 
            array (
                'apellido' => 'blanco',
                'cargo' => 'Gerente de Servicio',
                'ci' => '6377537',
                'dependencia' => 0,
                'direccion' => 'PLAZA VENEZUELA',
                'email' => 'IMPORMOTOR.GRTESERVICIO@GMAIL.COM',
                'estatus' => 1,
                'fecha_in' => '02-07-2016',
                'id_taller' => 1,
                'id_taller_personal' => 43,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'PEDRO',
                'observaciones' => '',
                'telefono' => '04142791604',
            ),
            20 => 
            array (
                'apellido' => 'guilarte',
                'cargo' => 'Mecánico',
                'ci' => '824350',
                'dependencia' => 0,
                'direccion' => 'guarena',
                'email' => 'inversionesserve@gamil.com',
                'estatus' => 1,
                'fecha_in' => '18-08-2016',
                'id_taller' => 1,
                'id_taller_personal' => 47,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'victor',
                'observaciones' => '',
                'telefono' => '04125352569',
            ),
            21 => 
            array (
                'apellido' => 'NAVAS',
                'cargo' => 'Mecánico',
                'ci' => '15167184',
                'dependencia' => 0,
                'direccion' => 'JUNQUITO',
                'email' => 'IMPORMOTOR.MECANICO@GMAIL.COM',
                'estatus' => 1,
                'fecha_in' => '18-08-2016',
                'id_taller' => 1,
                'id_taller_personal' => 50,
                'id_usuario' => 1,
                'jefe_taller' => 0,
                'nombre' => 'GABRIEL',
                'observaciones' => '',
                'telefono' => '04143252668',
            ),
            22 => 
            array (
                'apellido' => 'Quintero',
                'cargo' => 'Responsable',
                'ci' => '14912838',
                'dependencia' => 0,
                'direccion' => NULL,
                'email' => NULL,
                'estatus' => NULL,
                'fecha_in' => NULL,
                'id_taller' => 0,
                'id_taller_personal' => 120,
                'id_usuario' => 0,
                'jefe_taller' => 0,
                'nombre' => 'Anais',
                'observaciones' => NULL,
                'telefono' => NULL,
            ),
            23 => 
            array (
                'apellido' => 'Contreras',
                'cargo' => 'CHOFER',
                'ci' => '16857181',
                'dependencia' => 0,
                'direccion' => NULL,
                'email' => NULL,
                'estatus' => 1,
                'fecha_in' => NULL,
                'id_taller' => 0,
                'id_taller_personal' => 121,
                'id_usuario' => 0,
                'jefe_taller' => 0,
                'nombre' => 'Ricardo',
                'observaciones' => NULL,
                'telefono' => NULL,
            ),
        ));
        
        
    }
}