<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class PlanMantenimientoTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('plan_mantenimiento')->delete();
        
        \DB::table('plan_mantenimiento')->insert(array (
            0 => 
            array (
                'descripcion' => '',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 1,
                'id_usuario' => 76,
                'kilometraje' => 10000,
                'rango_max_k' => 8,
                'rango_max_t' => 10,
                'rango_min_k' => 7,
                'rango_min_t' => 6,
                'short' => 'M1',
                'tiempo' => 10,
                'tipo' => 0,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M1',
                'todas_marcasmodelos' => 0,
            ),
            1 => 
            array (
                'descripcion' => '',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 2,
                'id_usuario' => 76,
                'kilometraje' => 20000,
                'rango_max_k' => 15,
                'rango_max_t' => 18,
                'rango_min_k' => 14,
                'rango_min_t' => 14,
                'short' => 'M2',
                'tiempo' => 20,
                'tipo' => 0,
                'titulo' => 'PLAN 20.000 KM / 400 HORAS - RUTINA DE CAMBIO M2',
                'todas_marcasmodelos' => 0,
            ),
            2 => 
            array (
                'descripcion' => '',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 3,
                'id_usuario' => 76,
                'kilometraje' => 60000,
                'rango_max_k' => 22,
                'rango_max_t' => 26,
                'rango_min_k' => 21,
                'rango_min_t' => 22,
                'short' => 'M3',
                'tiempo' => 48,
                'tipo' => 0,
                'titulo' => 'PLAN 60.000 KM / 1200 HORAS - RUTINA DE CAMBIO M3',
                'todas_marcasmodelos' => 0,
            ),
            3 => 
            array (
                'descripcion' => '',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 4,
                'id_usuario' => 76,
                'kilometraje' => 100000,
                'rango_max_k' => 29,
                'rango_max_t' => 34,
                'rango_min_k' => 28,
                'rango_min_t' => 30,
                'short' => 'M4',
                'tiempo' => 10,
                'tipo' => 0,
                'titulo' => 'PLAN 100.000 KM / 2000 HORAS - RUTINA DE CAMBIO M4',
                'todas_marcasmodelos' => 0,
            ),
            4 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 150,
                'id_usuario' => 1,
                'kilometraje' => 10000,
                'rango_max_k' => 8,
                'rango_max_t' => 10,
                'rango_min_k' => 7,
                'rango_min_t' => 6,
                'short' => 'M1',
                'tiempo' => 10,
                'tipo' => 0,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M1',
                'todas_marcasmodelos' => 0,
            ),
            5 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 151,
                'id_usuario' => 1,
                'kilometraje' => 20000,
                'rango_max_k' => 15,
                'rango_max_t' => 18,
                'rango_min_k' => 14,
                'rango_min_t' => 14,
                'short' => 'M2',
                'tiempo' => 10,
                'tipo' => 0,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M2',
                'todas_marcasmodelos' => 0,
            ),
            6 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 152,
                'id_usuario' => 1,
                'kilometraje' => 40000,
                'rango_max_k' => 22,
                'rango_max_t' => 26,
                'rango_min_k' => 21,
                'rango_min_t' => 22,
                'short' => 'M3',
                'tiempo' => 10,
                'tipo' => 0,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M3',
                'todas_marcasmodelos' => 0,
            ),
            7 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 153,
                'id_usuario' => 1,
                'kilometraje' => 10000,
                'rango_max_k' => 29,
                'rango_max_t' => 34,
                'rango_min_k' => 28,
                'rango_min_t' => 30,
                'short' => NULL,
                'tiempo' => 10,
                'tipo' => 0,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M1',
                'todas_marcasmodelos' => 0,
            ),
            8 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 154,
                'id_usuario' => 1,
                'kilometraje' => 10000,
                'rango_max_k' => 36,
                'rango_max_t' => 42,
                'rango_min_k' => 35,
                'rango_min_t' => 38,
                'short' => NULL,
                'tiempo' => 10,
                'tipo' => 0,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M1',
                'todas_marcasmodelos' => 0,
            ),
            9 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 155,
                'id_usuario' => 1,
                'kilometraje' => 10000,
                'rango_max_k' => 43,
                'rango_max_t' => 50,
                'rango_min_k' => 42,
                'rango_min_t' => 46,
                'short' => NULL,
                'tiempo' => 10,
                'tipo' => 0,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M1',
                'todas_marcasmodelos' => 0,
            ),
            10 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 156,
                'id_usuario' => 1,
                'kilometraje' => 10000,
                'rango_max_k' => 50,
                'rango_max_t' => 58,
                'rango_min_k' => 49,
                'rango_min_t' => 54,
                'short' => NULL,
                'tiempo' => 10,
                'tipo' => 0,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M1',
                'todas_marcasmodelos' => 0,
            ),
            11 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 157,
                'id_usuario' => 1,
                'kilometraje' => 10000,
                'rango_max_k' => 57,
                'rango_max_t' => 66,
                'rango_min_k' => 56,
                'rango_min_t' => 62,
                'short' => NULL,
                'tiempo' => 10,
                'tipo' => 0,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M1',
                'todas_marcasmodelos' => 0,
            ),
            12 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 158,
                'id_usuario' => 1,
                'kilometraje' => 10000,
                'rango_max_k' => 64,
                'rango_max_t' => 74,
                'rango_min_k' => 63,
                'rango_min_t' => 70,
                'short' => NULL,
                'tiempo' => 10,
                'tipo' => 0,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M1',
                'todas_marcasmodelos' => 0,
            ),
            13 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 159,
                'id_usuario' => 1,
                'kilometraje' => 10000,
                'rango_max_k' => 71,
                'rango_max_t' => 82,
                'rango_min_k' => 70,
                'rango_min_t' => 78,
                'short' => NULL,
                'tiempo' => 10,
                'tipo' => 0,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M1',
                'todas_marcasmodelos' => 0,
            ),
            14 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ GRASA<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISION DE AIRE<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL DE DESGASTE TAMBORES Y BANDAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO<br><br>>>> ACTIVIDADES A Elevador Hidráulico<br>__Funcionamiento de los comandos<br>__Nivel de aceite hidráulico<br>__Ruteo y orden del cableado en general. Amarres T- rack<br>__Alineación de la plataforma<br>__Limpieza general<br><br>>> Pin de enganche<br>__Engrasar king pin<br>__Verificar juego con la quinta rueda<br>__Verificar diámetro de acople<br><br>>> Verificar Furgón<br>__Estado de láminas internas<br>__Estado de láminas externas<br>__Estado de las puertas<br>__Pases de agua<br><br>>>Suspensión Trasera<br>__Estado de las ballestas<br>__Estado de las guías<br>__Estado de los bujes<br>__Estado de los pulmones de la suspensión<br>__Estado de los soportes<br><br>>>Sistema Eléctrico<br>__Funcionamiento de las luces de la cava. Internas y externas<br>__Funcionamiento de luces de freno-cruce-emergencia.<br>__Estado de la fusiblera<br><br>>>Frenos.<br>__Estado de las bandas<br>__Estado de los raches. Verificar lubricación<br>__Estado de los tambores<br>__Graduación de las bandas<br>__Fugas de aire por los pulmones<br>__Estado de las mangueras de los pulmones<br>__Funcionamiento de las levas<br><br>>>Fugas de Aire<br>__Fugas por mangueras y conexiones chuto-cava<br>__Fugas por pulmones de frenos<br>__Fugas por tuberías y mangueras del sistema<br>__Fugas por valvula principal de frenos',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 162,
                'id_usuario' => 76,
                'kilometraje' => 10000,
                'rango_max_k' => 7500,
                'rango_max_t' => 250,
                'rango_min_k' => 6500,
                'rango_min_t' => 150,
                'short' => 'MT',
                'tiempo' => 10,
                'tipo' => 0,
                'titulo' => 'RUTINA DE MANTENIMIENTO TRAILER',
                'todas_marcasmodelos' => 1,
            ),
            15 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 163,
                'id_usuario' => 101,
                'kilometraje' => 10000,
                'rango_max_k' => 7500,
                'rango_max_t' => 250,
                'rango_min_k' => 6500,
                'rango_min_t' => 150,
                'short' => NULL,
                'tiempo' => 10,
                'tipo' => 0,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M1',
                'todas_marcasmodelos' => 0,
            ),
            16 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 164,
                'id_usuario' => 101,
                'kilometraje' => 10000,
                'rango_max_k' => 8,
                'rango_max_t' => 10,
                'rango_min_k' => 7,
                'rango_min_t' => 6,
                'short' => NULL,
                'tiempo' => 10,
                'tipo' => 0,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M1',
                'todas_marcasmodelos' => 0,
            ),
            17 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 165,
                'id_usuario' => 101,
                'kilometraje' => 10000,
                'rango_max_k' => 8000,
                'rango_max_t' => 8,
                'rango_min_k' => 6000,
                'rango_min_t' => 6,
                'short' => NULL,
                'tiempo' => 10,
                'tipo' => 0,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M1',
                'todas_marcasmodelos' => 0,
            ),
            18 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 166,
                'id_usuario' => 101,
                'kilometraje' => 10000,
                'rango_max_k' => 71,
                'rango_max_t' => 82,
                'rango_min_k' => 70,
                'rango_min_t' => 78,
                'short' => NULL,
                'tiempo' => 10,
                'tipo' => 0,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M1',
                'todas_marcasmodelos' => 0,
            ),
            19 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 167,
                'id_usuario' => 104,
                'kilometraje' => 10000,
                'rango_max_k' => 7500,
                'rango_max_t' => 9,
                'rango_min_k' => 6500,
                'rango_min_t' => 7,
                'short' => NULL,
                'tiempo' => 10,
                'tipo' => 0,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M1',
                'todas_marcasmodelos' => 0,
            ),
            20 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 168,
                'id_usuario' => 104,
                'kilometraje' => 10000,
                'rango_max_k' => 0,
                'rango_max_t' => 0,
                'rango_min_k' => 0,
                'rango_min_t' => 0,
                'short' => NULL,
                'tiempo' => 10,
                'tipo' => 2,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M1',
                'todas_marcasmodelos' => 0,
            ),
            21 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 169,
                'id_usuario' => 104,
                'kilometraje' => 10000,
                'rango_max_k' => 0,
                'rango_max_t' => 0,
                'rango_min_k' => 0,
                'rango_min_t' => 0,
                'short' => NULL,
                'tiempo' => 10,
                'tipo' => 2,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M1',
                'todas_marcasmodelos' => 0,
            ),
            22 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 170,
                'id_usuario' => 104,
                'kilometraje' => 10000,
                'rango_max_k' => 0,
                'rango_max_t' => 0,
                'rango_min_k' => 0,
                'rango_min_t' => 0,
                'short' => NULL,
                'tiempo' => 10,
                'tipo' => 2,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M1',
                'todas_marcasmodelos' => 0,
            ),
            23 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 171,
                'id_usuario' => 104,
                'kilometraje' => 10000,
                'rango_max_k' => 0,
                'rango_max_t' => 0,
                'rango_min_k' => 0,
                'rango_min_t' => 0,
                'short' => NULL,
                'tiempo' => 10,
                'tipo' => 2,
                'titulo' => 'PLAN 10.000 KM / 200 HORAS - RUTINA DE CAMBIO M1',
                'todas_marcasmodelos' => 0,
            ),
            24 => 
            array (
                'descripcion' => 'Realizar <br>Sndbdkaksjs<br>Sbdjdksksbs<br>Sjdjdksksa<br>Hdjsjsus',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 172,
                'id_usuario' => 104,
                'kilometraje' => 5000,
                'rango_max_k' => 8000,
                'rango_max_t' => -1,
                'rango_min_k' => 2000,
                'rango_min_t' => 5,
                'short' => NULL,
                'tiempo' => 2,
                'tipo' => 0,
                'titulo' => 'Plan prueba ',
                'todas_marcasmodelos' => 0,
            ),
            25 => 
            array (
                'descripcion' => '__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 173,
                'id_usuario' => 76,
                'kilometraje' => 6500,
                'rango_max_k' => 11000,
                'rango_max_t' => 220,
                'rango_min_k' => 9000,
                'rango_min_t' => 180,
                'short' => 'M1',
                'tiempo' => 1,
                'tipo' => 0,
                'titulo' => 'M1 STRALIS',
                'todas_marcasmodelos' => 0,
            ),
            26 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÃ“N FILTRO ACEITE MOTOR<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÃ“N DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISION<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERIA FRENOS HIDRAULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRAULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 174,
                'id_usuario' => 76,
                'kilometraje' => 6500,
                'rango_max_k' => 11000,
                'rango_max_t' => 220,
                'rango_min_k' => 9000,
                'rango_min_t' => 180,
                'short' => 'M1',
                'tiempo' => 1,
                'tipo' => 0,
                'titulo' => 'M1 TECTOR / EUROCARGO',
                'todas_marcasmodelos' => 0,
            ),
            27 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br>__ FILTRO COMBUSTIBLE<br>__ TRAMPA DE AGUA<br>__ FILTRO DE AIRE SECO<br>__ FILTRO DE AIRE EN BAÑO DE ACEITE<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÓN FILTRO DE ACEITE MOTOR<br>__ SUSTITUCIÓN FILTRO COMBUSTIBLE<br>__ SUSTITUCIÓN TRAMPA DE AGUA<br>__ SUSTITUCIÓN FILTRO DE AIRE SECO Y/O HÚMEDO<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÓN DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISIÓN<br>__ CONTROL DE PÉRDIDAS POR GRUPOS<br>__ CONTROL PÉRDIDA TUBERÍA FRENOS HIDRÁULICOS<br>__ CONTROL NIVEL LÍQUIDO DE FREOS HIDRÁULICOS<br>__ CONTROL DE DESGASTE DE DISCOS, PASTILLAS TAMBORES Y ZAPATOS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO<br>__ CONTROL DE ESTADO CORREAS DE MANDO VARIOS<br>__ CONTROL DE FIJACIÓN CAJA DIRECCIÓN Y SOPORTE<br>__ CONTROL DE TIRANTES RÓTULAS DE DIRECCIÓN<br>__ COMPROBAR APRIETE DE TUERCAS DE RUEDA',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 175,
                'id_usuario' => 76,
                'kilometraje' => 13000,
                'rango_max_k' => 11000,
                'rango_max_t' => 220,
                'rango_min_k' => 9000,
                'rango_min_t' => 180,
                'short' => 'M2',
                'tiempo' => 1,
                'tipo' => 0,
                'titulo' => 'M2 STRALIS',
                'todas_marcasmodelos' => 0,
            ),
            28 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br>__ FILTRO COMBUSTIBLE<br>__ TRAMPA DE AGUA<br>__ FILTRO DE AIRE SECO<br>__ FILTRO DE AIRE EN BAÑO DE ACEITE<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÓN FILTRO DE ACEITE MOTOR<br>__ SUSTITUCIÓN FILTRO COMBUSTIBLE<br>__ SUSTITUCIÓN TRAMPA DE AGUA<br>__ SUSTITUCIÓN FILTRO DE AIRE SECO Y/O HÚMEDO<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÓN DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISIÓN<br>__ CONTROL DE PÉRDIDAS POR GRUPOS<br>__ CONTROL PÉRDIDA TUBERÍA FRENOS HIDRÁULICOS<br>__ CONTROL NIVEL LÍQUIDO DE FREOS HIDRÁULICOS<br>__ CONTROL DE DESGASTE DE DISCOS, PASTILLAS TAMBORES Y ZAPATOS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO<br>__ CONTROL DE ESTADO CORREAS DE MANDO VARIOS<br>__ CONTROL DE FIJACIÓN CAJA DIRECCIÓN Y SOPORTE<br>__ CONTROL DE TIRANTES RÓTULAS DE DIRECCIÓN<br>__ COMPROBAR APRIETE DE TUERCAS DE RUEDA',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 176,
                'id_usuario' => 76,
                'kilometraje' => 13000,
                'rango_max_k' => 11000,
                'rango_max_t' => 220,
                'rango_min_k' => 9000,
                'rango_min_t' => 180,
                'short' => 'M2',
                'tiempo' => 1,
                'tipo' => 0,
                'titulo' => 'M2 TECTOR / EUROCARGO',
                'todas_marcasmodelos' => 0,
            ),
            29 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÓN FILTRO ACEITE MOTOR<br>__ SUSTITUCIÓN FILTRO COMBUSTIBLE<br>__ SUSTITUCIÓN TRAMPA DE AGUA<br>__ SUSTITUCIÓN FILTRO AIRE SECO Y/O HUMEDO<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÓN DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISIÓN<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERÍA FRENOS HIDRÁULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRÁULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO<br>__CONTROL DE ESTADO DE CORREAS Y MANDOS VARIOS<br>__CONTROL DE FIJACIÓN CAJA DE DIRECCIÓN Y SOPORTE<br>__CONTROL DE TIRANTES DE RÓTULAS DE DIRECCIÓN<br>__COMPROBAR APRIETE DE TUERCAS DE RUEDA<br>__SUSTITUCIÓN DE CORREAS DE DISTRIBUCIÓN Y ALTERNADOR<br>__SUSTITUCIÓN ACEITE DE GRUPOS Y ÓRGANOS<br>__SUSTITUCIÓN DE LÍQUIDO DE SISTEMA DE FRENO<br>__REVISIÓN DE INYECTORES EN BANCO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 177,
                'id_usuario' => 76,
                'kilometraje' => 26000,
                'rango_max_k' => 11000,
                'rango_max_t' => 220,
                'rango_min_k' => 9000,
                'rango_min_t' => 180,
                'short' => 'M3',
                'tiempo' => 1,
                'tipo' => 0,
                'titulo' => 'M3 STRALIS',
                'todas_marcasmodelos' => 0,
            ),
            30 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÓN FILTRO ACEITE MOTOR<br>__ SUSTITUCIÓN FILTRO COMBUSTIBLE<br>__ SUSTITUCIÓN TRAMPA DE AGUA<br>__ SUSTITUCIÓN FILTRO AIRE SECO Y/O HUMEDO<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÓN DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISIÓN<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERÍA FRENOS HIDRÁULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRÁULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO<br>__CONTROL DE ESTADO DE CORREAS Y MANDOS VARIOS<br>__CONTROL DE FIJACIÓN CAJA DE DIRECCIÓN Y SOPORTE<br>__CONTROL DE TIRANTES DE RÓTULAS DE DIRECCIÓN<br>__COMPROBAR APRIETE DE TUERCAS DE RUEDA<br>__SUSTITUCIÓN DE CORREAS DE DISTRIBUCIÓN Y ALTERNADOR<br>__SUSTITUCIÓN ACEITE DE GRUPOS Y ÓRGANOS<br>__SUSTITUCIÓN DE LÍQUIDO DE SISTEMA DE FRENO<br>__REVISIÓN DE INYECTORES EN BANCO',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 178,
                'id_usuario' => 76,
                'kilometraje' => 26000,
                'rango_max_k' => 11000,
                'rango_max_t' => 220,
                'rango_min_k' => 9000,
                'rango_min_t' => 180,
                'short' => 'M3',
                'tiempo' => 1,
                'tipo' => 0,
                'titulo' => 'M3 TECTOR / EUROCARGO',
                'todas_marcasmodelos' => 0,
            ),
            31 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ ACEITE CAJA DE CAMBIOS<br>__ACEITE DE TRANSMISIÓN AUTOMÁTICA<br>__ACEITE PUENTE<br>__ACEITE DE EJE DELANTERO<br>__ACEITE D/H<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br>__FILTRO DE COMBUSTIBLE<br>__TRAMPA DE AGUA<br>__FILTRO DE AIRE SECO<br>__FILTRO DE AIRE EN BAÑO DE ACEITE<br>__FILTRO D/H<br>__FILTRO SECANTE<br>__FILTRO DE TRANSMISIÓN AUTOMÁTICA<br>__CORREA DE ALTERNADOR<br>__CORREA COMPRESOR DE AIRE<br>__CORREA DISTRIBUCION<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÓN FILTRO ACEITE MOTOR<br>__ SUSTITUCIÓN TRAMPA DE AGUA<br>__ SUSTITUCIÓN FILTRO DE AIRE SECO Y/O HÚMEDO<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÓN DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISIÓN<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERÍA FRENOS HIDRÁULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRÁULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO<br>__ CONTROL DE ESTADO DE CORREAS DE MANDOS VARIOS<br>__ CONTROL DE FIJACIÓN CAJA DE DIRECCIÓN Y SOPORTE<br>__ CONTROL DE TIRANTES DE RÓTULAS DE DIRECCIÓN<br>__ COMPROBAR APRIETE DE TUERCAS DE RUEDA',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 179,
                'id_usuario' => 76,
                'kilometraje' => 52000,
                'rango_max_k' => 11000,
                'rango_max_t' => 220,
                'rango_min_k' => 9000,
                'rango_min_t' => 180,
                'short' => 'M4',
                'tiempo' => 1,
                'tipo' => 0,
                'titulo' => 'M4 STRALIS',
                'todas_marcasmodelos' => 0,
            ),
            32 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ ACEITE CAJA DE CAMBIOS<br>__ACEITE DE TRANSMISIÓN AUTOMÁTICA<br>__ACEITE PUENTE<br>__ACEITE DE EJE DELANTERO<br>__ACEITE D/H<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br>__FILTRO DE COMBUSTIBLE<br>__TRAMPA DE AGUA<br>__FILTRO DE AIRE SECO<br>__FILTRO DE AIRE EN BAÑO DE ACEITE<br>__FILTRO D/H<br>__FILTRO SECANTE<br>__FILTRO DE TRANSMISIÓN AUTOMÁTICA<br>__CORREA DE ALTERNADOR<br>__CORREA COMPRESOR DE AIRE<br>__CORREA DISTRIBUCION<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÓN FILTRO ACEITE MOTOR<br>__ SUSTITUCIÓN TRAMPA DE AGUA<br>__ SUSTITUCIÓN FILTRO DE AIRE SECO Y/O HÚMEDO<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÓN DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISIÓN<br>__ CONTROL DE PERDIDAS POR GRUPOS<br>__ CONTROL PERDIDA TUBERÍA FRENOS HIDRÁULICOS<br>__ CONTROL NIVEL LIQUIDO DE FRENOS HIDRÁULICOS<br>__ CONTROL DE DESGASTE DE DISCO, PASTILLAS TAMBORES Y ZAPATAS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO<br>__ CONTROL DE ESTADO DE CORREAS DE MANDOS VARIOS<br>__ CONTROL DE FIJACIÓN CAJA DE DIRECCIÓN Y SOPORTE<br>__ CONTROL DE TIRANTES DE RÓTULAS DE DIRECCIÓN<br>__ COMPROBAR APRIETE DE TUERCAS DE RUEDA',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 180,
                'id_usuario' => 76,
                'kilometraje' => 52000,
                'rango_max_k' => 11000,
                'rango_max_t' => 220,
                'rango_min_k' => 9000,
                'rango_min_t' => 180,
                'short' => 'M4',
                'tiempo' => 1,
                'tipo' => 0,
                'titulo' => 'M4 TECTOR / EUROCARGO',
                'todas_marcasmodelos' => 0,
            ),
            33 => 
            array (
                'descripcion' => '>>> REEMPLAZAR<br>__ ACEITE MOTOR<br>__ GRASA<br>__ FILTRO ACEITE MOTOR<br>__ FILTRO COMBUSTIBLE<br>__ TRAMPA DE AGUA<br>__ FILTRO DE AIRE SECO<br>__ FILTRO DE AIRE EN BAÑO DE ACEITE<br><br>>>> ACTIVIDADES A EJECUTAR<br>__ CAMBIO ACEITE MOTOR<br>__ SUSTITUCIÓN FILTRO DE ACEITE MOTOR<br>__ SUSTITUCIÓN FILTRO COMBUSTIBLE<br>__ SUSTITUCIÓN TRAMPA DE AGUA<br>__ SUSTITUCIÓN FILTRO DE AIRE SECO Y/O HÚMEDO<br>__ CONTROL DE APRIETE DE MANGUERAS Y ESTADO MANGUITOS ADMISIÓN DE AIRE<br>__ REAPRETAR ABRAZADERA MANGUITO SISTEMA ADMISIÓN<br>__ CONTROL DE PÉRDIDAS POR GRUPOS<br>__ CONTROL PÉRDIDA TUBERÍA FRENOS HIDRÁULICOS<br>__ CONTROL NIVEL LÍQUIDO DE FREOS HIDRÁULICOS<br>__ CONTROL DE DESGASTE DE DISCOS, PASTILLAS TAMBORES Y ZAPATOS DE FRENO<br>__ CONTROL NIVEL TODOS LOS FLUIDOS<br>__ ENGRASE GENERAL<br>__ PRUEBA FUNCIONAL Y OPERACIONES DE MOVIMIENTO<br>__ CONTROL DE ESTADO CORREAS DE MANDO VARIOS<br>__ CONTROL DE FIJACIÓN CAJA DIRECCIÓN Y SOPORTE<br>__ CONTROL DE TIRANTES RÓTULAS DE DIRECCIÓN<br>__ COMPROBAR APRIETE DE TUERCAS DE RUEDA',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 181,
                'id_usuario' => 76,
                'kilometraje' => 6500,
                'rango_max_k' => 21000,
                'rango_max_t' => 405,
                'rango_min_k' => 19000,
                'rango_min_t' => 395,
                'short' => NULL,
                'tiempo' => 1,
                'tipo' => 0,
                'titulo' => 'M2 EUROCARGO',
                'todas_marcasmodelos' => 0,
            ),
            34 => 
            array (
                'descripcion' => 'Cambio de aceite y filtro de motor para vehiculos y camionetas ',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 182,
                'id_usuario' => 104,
                'kilometraje' => 5000,
                'rango_max_k' => 5500,
                'rango_max_t' => 0,
                'rango_min_k' => 4500,
                'rango_min_t' => 2,
                'short' => NULL,
                'tiempo' => 1,
                'tipo' => 0,
                'titulo' => 'Cambio de Aceite y Filtro Vehiculos ',
                'todas_marcasmodelos' => 0,
            ),
            35 => 
            array (
                'descripcion' => 'Reemplazo de Kit de Filtros<br>filtros de aceite <br>filtros de gasoil<br>filtro trampa de agua<br>Filtro de Aire',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 183,
                'id_usuario' => 104,
                'kilometraje' => 5000,
                'rango_max_k' => 5500,
                'rango_max_t' => 3,
                'rango_min_k' => 4500,
                'rango_min_t' => 1,
                'short' => NULL,
                'tiempo' => 2,
                'tipo' => 0,
                'titulo' => 'Cambio de Aceite y Filtro Chuto',
                'todas_marcasmodelos' => 0,
            ),
            36 => 
            array (
                'descripcion' => 'mantenimiento preventivo autobus 2',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 184,
                'id_usuario' => 76,
                'kilometraje' => 7500,
                'rango_max_k' => 17999,
                'rango_max_t' => 5,
                'rango_min_k' => 1,
                'rango_min_t' => 1,
                'short' => NULL,
                'tiempo' => 3,
                'tipo' => 0,
                'titulo' => 'mantenimiento preventivo autobus iveco 2 placas a1199ad',
                'todas_marcasmodelos' => 0,
            ),
            37 => 
            array (
                'descripcion' => ' Preventivo  Mitsubishi Canter',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 185,
                'id_usuario' => 76,
                'kilometraje' => 7500,
                'rango_max_k' => 14000,
                'rango_max_t' => 1,
                'rango_min_k' => 1000,
                'rango_min_t' => 5,
                'short' => NULL,
                'tiempo' => 3,
                'tipo' => 0,
                'titulo' => 'Mtto. Preventivo  Mitsubishi Canter',
                'todas_marcasmodelos' => 0,
            ),
            38 => 
            array (
                'descripcion' => 'M1',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 186,
                'id_usuario' => 76,
                'kilometraje' => 6500,
                'rango_max_k' => 6500,
                'rango_max_t' => 1,
                'rango_min_k' => 6500,
                'rango_min_t' => 1,
                'short' => NULL,
                'tiempo' => 1,
                'tipo' => 0,
                'titulo' => 'M1',
                'todas_marcasmodelos' => 0,
            ),
            39 => 
            array (
                'descripcion' => 'DAILY',
                'id_marca' => 0,
                'id_modelo' => '',
                'id_plan' => 187,
                'id_usuario' => 76,
                'kilometraje' => 6500,
                'rango_max_k' => 12999,
                'rango_max_t' => 3,
                'rango_min_k' => 1,
                'rango_min_t' => 1,
                'short' => NULL,
                'tiempo' => 2,
                'tipo' => 0,
                'titulo' => 'M1',
                'todas_marcasmodelos' => 0,
            ),
        ));
        
        
    }
}