<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SuministrosComprasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('suministros_compras')->delete();
        
        \DB::table('suministros_compras')->insert(array (
            0 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-14 12:42:40',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 2,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 74,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-14 12:42:40',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 1,
            ),
            1 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-14 13:12:56',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 3,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 75,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-14 13:12:56',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 1,
            ),
            2 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-18 11:23:01',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 4,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 76,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-18 11:23:01',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 1,
            ),
            3 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-18 11:25:16',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 5,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 77,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-18 11:25:16',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 1,
            ),
            4 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-19 09:57:22',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 6,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 83,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-19 09:57:22',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 1,
            ),
            5 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-19 11:12:44',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 7,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 84,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-19 11:12:44',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 1,
            ),
            6 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-19 12:55:18',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 8,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 85,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-19 12:55:18',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 1,
            ),
            7 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-19 17:48:45',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 9,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 89,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-19 17:48:45',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 1,
            ),
            8 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-21 11:20:06',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 10,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 90,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-24 18:35:47',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            9 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-21 13:51:42',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 11,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 91,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-21 13:51:42',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            10 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-24 12:04:47',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 12,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 96,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-24 12:04:47',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            11 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-24 12:08:10',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 13,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 97,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-24 12:08:10',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            12 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-24 15:11:24',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 14,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 98,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-24 15:11:24',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            13 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-24 15:21:55',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 15,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 99,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-24 15:21:55',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            14 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-24 15:29:28',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 16,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 100,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-24 15:29:28',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            15 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-24 15:31:48',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 17,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 101,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-24 15:31:48',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            16 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-24 16:45:48',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 18,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 102,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-24 16:45:48',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            17 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-24 17:36:44',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 19,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 103,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-24 17:36:44',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            18 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-25 10:18:49',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 20,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 104,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-25 10:18:49',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            19 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-25 13:54:20',
                'estatus' => 4,
                'foto_factura' => NULL,
                'id' => 21,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 105,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-25 13:54:20',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            20 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-26 09:58:49',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 27,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 111,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-26 09:58:49',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            21 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-26 09:46:31',
                'estatus' => 3,
                'foto_factura' => NULL,
                'id' => 26,
                'observacion' => NULL,
                'observacion_admin' => 'PRUEBAS',
                'orden_id' => 110,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-10 19:12:33',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            22 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-26 10:23:10',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 28,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 112,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-26 10:23:10',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 9,
            ),
            23 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-26 12:37:26',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 29,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 113,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-26 12:37:26',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 9,
            ),
            24 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-28 10:35:32',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 30,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 114,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-28 10:35:32',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            25 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-28 10:51:47',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 31,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 115,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-28 10:51:47',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            26 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-11-28 10:56:11',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 32,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 117,
                'referencia_compra' => NULL,
                'updated_at' => '2025-11-28 10:56:11',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            27 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-01 09:59:37',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 33,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 118,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-01 09:59:37',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            28 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-01 10:08:55',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 34,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 119,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-01 10:08:55',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            29 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-04 10:41:32',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 35,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 120,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-04 10:41:32',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            30 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-04 10:42:50',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 36,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 121,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-04 10:42:50',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            31 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-05 10:11:42',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 37,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 122,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-05 10:11:42',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 9,
            ),
            32 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-05 12:21:49',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 38,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 123,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-05 12:21:49',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            33 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-05 15:14:44',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 39,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 124,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-05 15:14:44',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            34 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-08 10:04:43',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 40,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 125,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-08 10:04:43',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            35 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-08 10:11:15',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 41,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 126,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-08 10:11:15',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            36 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-08 17:16:41',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 42,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 128,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-08 17:16:41',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            37 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-09 09:54:00',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 43,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 129,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-09 09:54:00',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            38 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-09 10:00:36',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 44,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 130,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-09 10:00:36',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            39 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-09 10:04:28',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 45,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 131,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-09 10:04:28',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            40 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-09 10:40:57',
                'estatus' => 2,
                'foto_factura' => NULL,
                'id' => 46,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 132,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-09 12:41:28',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            41 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-09 12:27:19',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 47,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 133,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-09 12:27:19',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            42 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-09 12:34:59',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 48,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 134,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-09 12:34:59',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            43 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-09 13:16:03',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 49,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 135,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-09 13:16:03',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            44 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-09 16:50:00',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 50,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 136,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-09 16:50:00',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            45 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-10 12:59:44',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 51,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 137,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-10 12:59:44',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            46 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-11 13:51:16',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 52,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 138,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-11 13:51:16',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            47 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-11 15:33:04',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 53,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 139,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-11 15:33:04',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            48 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-11 17:04:57',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 54,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 140,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-11 17:04:57',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            49 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-12 11:49:35',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 55,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 141,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-12 11:49:35',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            50 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-12 13:52:50',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 56,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 142,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-12 13:52:50',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            51 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-15 11:11:22',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 57,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 143,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-15 11:11:22',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            52 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-15 11:11:32',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 58,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 144,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-15 11:11:32',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            53 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-15 16:27:06',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 59,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 145,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-15 16:27:06',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            54 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-17 13:57:49',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 60,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 146,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-17 13:57:49',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            55 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-23 11:24:57',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 61,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 147,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-23 11:24:57',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            56 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-23 11:31:28',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 62,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 148,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-23 11:31:28',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            57 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-26 09:55:01',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 63,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 149,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-26 09:55:01',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            58 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-29 11:57:56',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 64,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 150,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-29 11:57:56',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            59 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-29 11:58:40',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 65,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 151,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-29 11:58:40',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            60 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-29 12:00:29',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 66,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 152,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-29 12:00:29',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            61 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-29 12:05:05',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 67,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 153,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-29 12:05:05',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            62 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-30 10:11:10',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 68,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 154,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-30 10:11:10',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            63 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-30 10:11:13',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 69,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 155,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-30 10:11:13',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            64 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2025-12-30 18:39:53',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 70,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 157,
                'referencia_compra' => NULL,
                'updated_at' => '2025-12-30 18:39:53',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            65 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-07 09:34:44',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 71,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 158,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-07 09:34:44',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            66 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-07 09:35:40',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 72,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 159,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-07 09:35:40',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            67 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-07 09:36:45',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 73,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 160,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-07 09:36:45',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            68 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-07 09:37:38',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 74,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 161,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-07 09:37:38',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            69 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-08 11:27:53',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 75,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 162,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-08 11:27:53',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            70 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-08 11:31:33',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 76,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 163,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-08 11:31:33',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            71 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-09 11:08:38',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 77,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 164,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-09 11:08:38',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            72 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-12 11:58:18',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 78,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 165,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-12 11:58:18',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            73 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-12 15:51:58',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 79,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 166,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-12 15:51:58',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            74 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-12 15:52:04',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 80,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 167,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-12 15:52:04',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            75 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-12 15:52:13',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 81,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 168,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-12 15:52:13',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            76 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-13 17:04:10',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 82,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 169,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-13 17:04:10',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            77 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-14 12:18:47',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 83,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 170,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-14 12:18:47',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            78 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-14 14:17:23',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 84,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 171,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-14 14:17:23',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            79 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-15 17:16:51',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 85,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 172,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-15 17:16:51',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            80 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-16 10:49:01',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 86,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 173,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-16 10:49:01',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            81 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-16 12:39:42',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 87,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 174,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-16 12:39:42',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            82 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-16 14:09:55',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 88,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 175,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-16 14:09:55',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            83 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-16 14:13:50',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 89,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 176,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-16 14:13:50',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            84 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-19 12:09:31',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 90,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 177,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-19 12:09:31',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            85 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-19 16:11:22',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 91,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 178,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-19 16:11:22',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            86 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-20 10:02:08',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 92,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 179,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-20 10:02:08',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            87 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-20 11:36:31',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 93,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 180,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-20 11:36:31',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            88 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-20 11:51:09',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 94,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 181,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-20 11:51:09',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            89 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-20 11:56:05',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 95,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 182,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-20 11:56:05',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
            90 => 
            array (
                'costo_total' => NULL,
                'created_at' => '2026-01-20 15:35:59',
                'estatus' => 1,
                'foto_factura' => NULL,
                'id' => 96,
                'observacion' => NULL,
                'observacion_admin' => NULL,
                'orden_id' => 183,
                'referencia_compra' => NULL,
                'updated_at' => '2026-01-20 15:35:59',
                'usuario_aprobador_id' => NULL,
                'usuario_solicitante_id' => 495,
            ),
        ));
        
        
    }
}