<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class TabuladorViaticosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('tabulador_viaticos')->delete();
        
        \DB::table('tabulador_viaticos')->insert(array (
            0 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'PLANTA GUATIRE',
                'id' => 1,
                'pago_ayudante' => '0.00',
                'pago_chofer' => '30.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'PLANTA PDVSA',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '10.00',
            ),
            1 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'PLANTA GUARAGUAO',
                'id' => 2,
                'pago_ayudante' => '35.00',
                'pago_chofer' => '70.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 6,
                'tipo_viaje' => 'PLANTA PDVSA',
                'updated_at' => '2025-10-15 12:21:43',
                'viatico_almuerzo' => '30.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '20.00',
            ),
            2 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'PLANTA PALITO',
                'id' => 3,
                'pago_ayudante' => '25.00',
                'pago_chofer' => '50.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 7,
                'tipo_viaje' => 'PLANTA PDVSA',
                'updated_at' => '2025-10-15 12:15:06',
                'viatico_almuerzo' => '30.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '20.00',
            ),
            3 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'PLANTA YAGUA',
                'id' => 4,
                'pago_ayudante' => '25.00',
                'pago_chofer' => '50.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 5,
                'tipo_viaje' => 'PLANTA PDVSA',
                'updated_at' => NULL,
                'viatico_almuerzo' => '30.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '20.00',
            ),
            4 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'PLANTA SANTA LUCIA ',
                'id' => 5,
                'pago_ayudante' => '15.00',
                'pago_chofer' => '30.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'PLANTA PDVSA',
                'updated_at' => NULL,
                'viatico_almuerzo' => '30.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '20.00',
            ),
            5 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'LA GUAIRA',
                'id' => 6,
                'pago_ayudante' => '5.00',
                'pago_chofer' => '10.00',
                'pago_chofer_ejecutivo' => '10.00',
                'peajes' => 0,
                'tipo_viaje' => 'VIAJE LARGO',
                'updated_at' => '2025-10-15 13:04:01',
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '0.00',
            ),
            6 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'BARQUISIMETO',
                'id' => 7,
                'pago_ayudante' => '25.00',
                'pago_chofer' => '50.00',
                'pago_chofer_ejecutivo' => '30.00',
                'peajes' => 12,
                'tipo_viaje' => 'VIAJE LARGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '30.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '20.00',
            ),
            7 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'BARINAS',
                'id' => 8,
                'pago_ayudante' => '25.00',
                'pago_chofer' => '50.00',
                'pago_chofer_ejecutivo' => '30.00',
                'peajes' => 16,
                'tipo_viaje' => 'VIAJE LARGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '30.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '20.00',
            ),
            8 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'VALENCIA',
                'id' => 9,
                'pago_ayudante' => '15.00',
                'pago_chofer' => '30.00',
                'pago_chofer_ejecutivo' => '20.00',
                'peajes' => 6,
                'tipo_viaje' => 'VIAJE LARGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '30.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '20.00',
            ),
            9 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'GUARICO',
                'id' => 10,
                'pago_ayudante' => '25.00',
                'pago_chofer' => '50.00',
                'pago_chofer_ejecutivo' => '30.00',
                'peajes' => 16,
                'tipo_viaje' => 'VIAJE LARGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '30.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '20.00',
            ),
            10 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'HIGUEROTE',
                'id' => 11,
                'pago_ayudante' => '10.00',
                'pago_chofer' => '20.00',
                'pago_chofer_ejecutivo' => '15.00',
                'peajes' => 0,
                'tipo_viaje' => 'VIAJE LARGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '30.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '20.00',
            ),
            11 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'FALCON',
                'id' => 12,
                'pago_ayudante' => '25.00',
                'pago_chofer' => '50.00',
                'pago_chofer_ejecutivo' => '30.00',
                'peajes' => 10,
                'tipo_viaje' => 'VIAJE LARGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '30.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '20.00',
            ),
            12 => 
            array (
                'costo_pernocta' => '100.00',
                'created_at' => NULL,
                'destino' => 'CUIDAD BOLIVAR',
                'id' => 13,
                'pago_ayudante' => '45.00',
                'pago_chofer' => '90.00',
                'pago_chofer_ejecutivo' => '70.00',
                'peajes' => 12,
                'tipo_viaje' => 'VIAJE LARGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '60.00',
                'viatico_cena' => '60.00',
                'viatico_desayuno' => '40.00',
            ),
            13 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'MARACAY',
                'id' => 14,
                'pago_ayudante' => '10.00',
                'pago_chofer' => '20.00',
                'pago_chofer_ejecutivo' => '15.00',
                'peajes' => 2,
                'tipo_viaje' => 'VIAJE LARGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '30.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '20.00',
            ),
            14 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'CAGUA ',
                'id' => 15,
                'pago_ayudante' => '10.00',
                'pago_chofer' => '20.00',
                'pago_chofer_ejecutivo' => '15.00',
                'peajes' => 2,
                'tipo_viaje' => 'VIAJE LARGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '30.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '20.00',
            ),
            15 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'PUERTO LA CRUZ',
                'id' => 16,
                'pago_ayudante' => '35.00',
                'pago_chofer' => '70.00',
                'pago_chofer_ejecutivo' => '30.00',
                'peajes' => 6,
                'tipo_viaje' => 'VIAJE LARGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '30.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '20.00',
            ),
            16 => 
            array (
                'costo_pernocta' => '100.00',
                'created_at' => NULL,
                'destino' => 'MATURIN',
                'id' => 17,
                'pago_ayudante' => '35.00',
                'pago_chofer' => '70.00',
                'pago_chofer_ejecutivo' => '50.00',
                'peajes' => 6,
                'tipo_viaje' => 'VIAJE LARGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '60.00',
                'viatico_cena' => '60.00',
                'viatico_desayuno' => '40.00',
            ),
            17 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'CHARALLAVE',
                'id' => 18,
                'pago_ayudante' => '2.50',
                'pago_chofer' => '5.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 2,
                'tipo_viaje' => 'VIAJE LARGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '0.00',
            ),
            18 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'LA GRAN CARACAS',
                'id' => 19,
                'pago_ayudante' => '2.50',
                'pago_chofer' => '5.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'DESPACHO DE COMBUSTILE',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '0.00',
            ),
            19 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'ANZOATEGUI',
                'id' => 20,
                'pago_ayudante' => '15.00',
                'pago_chofer' => '90.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 6,
                'tipo_viaje' => 'VIAJE LARGO',
                'updated_at' => '2025-11-06 15:28:04',
                'viatico_almuerzo' => '30.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '20.00',
            ),
            20 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'COJEDES',
                'id' => 21,
                'pago_ayudante' => '15.00',
                'pago_chofer' => '30.00',
                'pago_chofer_ejecutivo' => '20.00',
                'peajes' => 6,
                'tipo_viaje' => 'VIAJE LARGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '30.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '20.00',
            ),
            21 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'PLANTA BAJO GRANDE - MARACAIBO',
                'id' => 22,
                'pago_ayudante' => '15.00',
                'pago_chofer' => '30.00',
                'pago_chofer_ejecutivo' => '20.00',
                'peajes' => 6,
                'tipo_viaje' => 'PLANTA PDVSA',
                'updated_at' => NULL,
                'viatico_almuerzo' => '30.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '20.00',
            ),
            22 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'MARACAIBO',
                'id' => 23,
                'pago_ayudante' => '15.00',
                'pago_chofer' => '30.00',
                'pago_chofer_ejecutivo' => '20.00',
                'peajes' => 6,
                'tipo_viaje' => 'VIAJE LARGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '30.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '20.00',
            ),
            23 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'Planta termoelectrica Jose Maria España',
                'id' => 24,
                'pago_ayudante' => '2.50',
                'pago_chofer' => '5.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'PLANTA TERMOELECTRICA JME',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '0.00',
            ),
            24 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'CAICAGUITA',
                'id' => 25,
                'pago_ayudante' => '0.00',
                'pago_chofer' => '30.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'VIAJE CORTO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '10.00',
            ),
            25 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'ALTO HATILLO',
                'id' => 26,
                'pago_ayudante' => '2.50',
                'pago_chofer' => '5.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'DESPACHO DE COMBUSTILE',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '0.00',
            ),
            26 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'PUERTO CABELLO',
                'id' => 27,
                'pago_ayudante' => '15.00',
                'pago_chofer' => '30.00',
                'pago_chofer_ejecutivo' => '20.00',
                'peajes' => 6,
                'tipo_viaje' => 'VIAJE LARGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '30.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '20.00',
            ),
            27 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'PUERTO LA CRUZ - GUARAGUAO',
                'id' => 28,
                'pago_ayudante' => '0.00',
                'pago_chofer' => '0.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'MGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '0.00',
            ),
            28 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'PTO ORDAZ',
                'id' => 29,
                'pago_ayudante' => '0.00',
                'pago_chofer' => '0.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'MGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '0.00',
            ),
            29 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'GUANTA - ANZOATEGUI',
                'id' => 30,
                'pago_ayudante' => '0.00',
                'pago_chofer' => '0.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'MGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '0.00',
            ),
            30 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'PTA CARDON - FALCON',
                'id' => 31,
                'pago_ayudante' => '0.00',
                'pago_chofer' => '0.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'MGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '0.00',
            ),
            31 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'MARINA CARABALLEDA - LA GUAIRA',
                'id' => 32,
                'pago_ayudante' => '0.00',
                'pago_chofer' => '0.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'MGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '0.00',
            ),
            32 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'CLUB PTO AZUL LA GUAIRA',
                'id' => 33,
                'pago_ayudante' => '0.00',
                'pago_chofer' => '0.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'MGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '0.00',
            ),
            33 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'CLUB CAMURI GRANDE',
                'id' => 34,
                'pago_ayudante' => '0.00',
                'pago_chofer' => '0.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'MGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '0.00',
            ),
            34 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'MARINA DE ARRECIFE',
                'id' => 35,
                'pago_ayudante' => '0.00',
                'pago_chofer' => '0.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'MGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '0.00',
            ),
            35 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'CIRCULO MILITAR MAMO',
                'id' => 36,
                'pago_ayudante' => '0.00',
                'pago_chofer' => '0.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'MGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '0.00',
            ),
            36 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'GUAMACHE - NUEVA ESPARTA',
                'id' => 37,
                'pago_ayudante' => '0.00',
                'pago_chofer' => '0.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'MGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '0.00',
            ),
            37 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'ARAURE - PORTUGUESA',
                'id' => 38,
                'pago_ayudante' => '0.00',
                'pago_chofer' => '0.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'MGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '0.00',
            ),
            38 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'PTO LA CEIBA - TRUJILLO',
                'id' => 39,
                'pago_ayudante' => '0.00',
                'pago_chofer' => '0.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'MGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '0.00',
            ),
            39 => 
            array (
                'costo_pernocta' => '0.00',
                'created_at' => NULL,
                'destino' => 'Playa Grande',
                'id' => 40,
                'pago_ayudante' => '0.00',
                'pago_chofer' => '0.00',
                'pago_chofer_ejecutivo' => '0.00',
                'peajes' => 0,
                'tipo_viaje' => 'MGO',
                'updated_at' => NULL,
                'viatico_almuerzo' => '0.00',
                'viatico_cena' => '0.00',
                'viatico_desayuno' => '0.00',
            ),
        ));
        
        
    }
}